### ISSUE TITLE
Cannon Softlock

### ISSUE THREAD

**Issue by somario360** [djoslin0/sm64ex-coop#1]
When trying to open the cannon in a level (so far tested in BOB & WF) the cannon dialogue will repeat infinitely. Sometimes the cannon will open, but the game will crash after.

**Comment by somario360** [comment]
The same problem also occurs with the owl in WF.

**Comment by djoslin0** [comment]
Thanks for the bug report!
I believe this is now fixed.

**Comment by djoslin0** [comment]
Let me know if this should be reopened.
