### ISSUE TITLE
Feature request: Headless Version

### ISSUE THREAD

**Issue by pjalsGit** [djoslin0/sm64ex-coop#104]
host a server without opening the game

no, the server does not consume a playerslot

**Comment by IoIxD** [comment]
I second this, I want to be able to host a 24/7 server on my rented VPS

**Comment by IoIxD** [comment]
Actually it turns out that hosting through Discord gets around my ISP having blocked my ability to port forward, so I don't actually need this. Would still be nice to have.

**Comment by djoslin0** [comment]
This is done.

Added headless server as a compile setting:
`make -j RENDER_API=DUMMY AUDIO_API=DUMMY CONTROLLER_API=`

Run the server like so:
`./build/us_pc/sm64.us.f3dex2e.exe --server 7777`

The server's player is hidden from other players. They still consume a slot, but that would be significantly hard to change at this point.
