### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by Beyley** [djoslin0/sm64ex-coop#106]
**Describe the bug**
Game does not launch, only a white window opens, then the game closes

**To Reproduce**
UNKNOWN

**Expected behavior**
Game opens as normal

**Screenshots**
https://images-ext-2.discordapp.net/external/RCsgBT8yWjOZ89yuNWEsl44f-YwXj3VC9CiEVdaxQrc/https/i.imgur.com/s1OgjMA.png

**Desktop (please complete the following information):**
 - OS: Windows 10
https://images-ext-1.discordapp.net/external/SxRolUzWtrY6r5pzZmGWcvF1wdqr8IttIkeGYBYtkKc/https/i.imgur.com/Hg1hxEs.png

**Additional context**
This is not my computer, this is my friends

**Comment by RGG200** [comment]
i have the same error

**Comment by DamianS-eng** [comment]
You need all the files and folders created in the build folder next to the executable, or the game will not launch. The executable alone is not enough.

**Comment by Beyley** [comment]
> You need all the files and folders created in the build folder next to the executable, or the game will not launch. The executable alone is not enough.

we did have that
