### ISSUE TITLE
Web Building seems to not generate the correct files

### ISSUE THREAD

**Issue by Faithy3** [djoslin0/sm64ex-coop#108]
**Describe the bug**

When building for web using instructions on the sm64ex wiki, the html file, among other things, are simply not generated.

**To Reproduce**
1. Clone repository
2. Clone emscripten-core/emsdk
3. in emsdk, run `./emsdk install latest`, then `emsdk activate latest`
4. cd to sm64ex-coop
5. Build with `make TARGET_WEB=1`
6. cd to build folder
7. view resulting build files

**Expected behavior**
Build is similar to sm64ex, with html, js, etc. files for hosting on web.

**Screenshots**
I'll include a terminal screenshot of the output files, compared to the sm64ex output files
![image](https://user-images.githubusercontent.com/29293388/117577331-38406e00-b09e-11eb-8316-1d5e1fb3c9e7.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.10
 - Browser: Firefox (not sure why that's important)
 - Version: (Firefox version or commit version? I'm on 88.0 and 85984da respectively)

**Smartphone (please complete the following information):**
uhh?????

**Additional context**
I'm not sure if this is intended or not, I'd really love if this was allowed to work on web, multiplayer web-based SM64 would be super fun.

**Comment by fgsfdsfgs** [comment]
I don't think this would even work on web, unless emscripten magically translates POSIX UDP socket calls to websockets or something.

**Comment by djoslin0** [comment]
I won't be working on porting this to the web
