### ISSUE TITLE
"Respawned Ship" bug

### ISSUE THREAD

**Issue by IAmTheRealXYZ** [djoslin0/sm64ex-coop#109]
**Describe the bug**
The following bug causes the ship in "Dire, Dire Docks" to appear, regardless of the star mission that you chose, on top of that, it teleports the other player to the main player, which causes the respawn of the ship to happen, and also causes the catchable moving rods thingies to dispawn.
This makes the 8 red coins mission impossible.

**To Reproduce**
1. Go to the middle part of the "tunnel" (I hope it's technically a tunnel)
And there you go! the glitch is here!

**Expected behavior**
The teleportation should never happen, and the ship should never appear if any mission besides 1 has been chosen.

**Screenshots:**
*No screenshots available*

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
*No additional context available*

**Comment by Sunketchupm** [comment]
The sub only despawns after collecting the second key, the chosen star doesn't matter.

**Comment by djoslin0** [comment]
Everything is working as intended here, although it is strange.
