### ISSUE TITLE
(Minor) Sleep Sound Bug

### ISSUE THREAD

**Issue by somario360** [djoslin0/sm64ex-coop#11]
When one player goes into the laying down sleep animation, the sleeping sound will keep playing for the other player after they wake up and will not play voiceclips as well, this is fixed when the player takes damage. Also when they wake up, the music will still stay quieter for the other player.

**Comment by djoslin0** [comment]
Fixed in https://github.com/djoslin0/sm64ex-coop/commit/f62f80a2289af60b37058d2bdfccf6003c3f9ecf
