### ISSUE TITLE
Doesn't compile on rpi4 due to unrecognized emulation mode

### ISSUE THREAD

**Issue by M3KAI5ER44** [djoslin0/sm64ex-coop#111]
I used `make BETTERCAMERA=1 EXTERNAL_DATA=1 -j4 TARGET_RPI=1 DISCORDRPC=0 DISCORD_SDK=0`
error: `ld: unrecognised emulation mode: fpu=neon-vfpv4
Supported emulations: armelf_linux_eabi armelfb_linux_eabi
make: *** [Makefile:1100: build/us_pc/sm64.us.f3dex2e.arm] Error 1`
Im clueless.

**Comment by djoslin0** [comment]
Are you able to compile sm64ex (not coop) on rpi4?

**Comment by M3KAI5ER44** [comment]
Testing...

**Comment by M3KAI5ER44** [comment]
Yes, albeit without sound but that doesn't matter atm

**Comment by M3KAI5ER44** [comment]
Anything?

**Comment by M3KAI5ER44** [comment]
Is there anything I can do about the issue?

**Comment by Llennpie** [comment]
I'm pretty sure Discord's Game SDK doesn't support ARM. This may be unrelated to the error, but I don't think you'll get coop working on RPI at all.

**Comment by djoslin0** [comment]
Try making with Discord's SDK disabled:
`make clean ; make DISCORD_SDK=0`

That's my best guess, though I doubt it will perform that well on a RPI if you can get it to build.

**Comment by M3KAI5ER44** [comment]
> I used `make BETTERCAMERA=1 EXTERNAL_DATA=1 -j4 TARGET_RPI=1 DISCORDRPC=0 DISCORD_SDK=0`

**Comment by biosith** [comment]
Still unable to build, getting the following error when I attempt:

/usr/bin/ld: lib/lua/linux/liblua53.a: error adding symbols: file format not recognized
collect2: error: ld returned 1 exit status
make: *** [Makefile:1562: build/us_pc/sm64.us.f3dex2e.arm] Error 1

**Comment by Isaac0-dev** [comment]
this can be fixed by compiling your own lua libraries. co-op might get native support later on. just keep in mind I have an rpi 3B+.

**Comment by biosith** [comment]
> this can be fixed by compiling your own lua libraries. co-op might get native support later on. just keep in mind I have an rpi 3B+.

So I did this and also had to replace the libbass.so and libbass_fx.so libraries but after all that it did compile and ran. Thanks for the help

**Comment by Isaac0-dev** [comment]
No problem. congrats on being the second person to compile co-op on a raspberry pi as far as I know.

**Comment by M3KAI5ER44** [comment]
After giving it another go on building for rpi4 with the latest commits, it seems the build goes smoothly with the same `make BETTERCAMERA=1 EXTERNAL_DATA=1 -j4 TARGET_RPI=1 DISCORDRPC=0 DISCORD_SDK=0` command I previously used and the Linux build instructions from the wiki. Thanks, everyone.
