### ISSUE TITLE
Mac build fails with DISCORD_SDK=1

### ISSUE THREAD

**Issue by NickHam13** [djoslin0/sm64ex-coop#113]
This issue is already known, just putting it here so it can be tracked.

Attempting to build on Mac with the build option `DISCORD_SDK=1` results with:
`ld: library not found for -ldiscord_game_sdk`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`gmake: *** [Makefile:1096: build/us_pc/sm64.us.f3dex2e] Error 1`

It's possible to build the game on Mac without the Discord SDK by using `DISCORD_SDK=0`.

**Comment by fgsfdsfgs** [comment]
Do you have GNU binutils installed? OSX's `cp` behaves a little bit differently, so `gcp` is used instead in the Makefile.

**Comment by NickHam13** [comment]
> 
> 
> Do you have GNU binutils installed? OSX's `cp` behaves a little bit differently, so `gcp` is used instead in the Makefile.

Yeah, I have them.

**Comment by fgsfdsfgs** [comment]
What about coreutils? `gcp` might be in there instead, I don't recall.

**Comment by NickHam13** [comment]
> 
> 
> What about coreutils? `gcp` might be in there instead, I don't recall.
> Should be something like `brew install coreutils`

That got it farther, but it results in a different error:
`ld: library not found for -ldiscord_game_sdk`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`gmake: *** [Makefile:1096: build/us_pc/sm64.us.f3dex2e] Error 1`

**Comment by fgsfdsfgs** [comment]
First, make sure that your repo is up to date (`make clean && git checkout unstable && git pull` and then rebuild), then if it still doesn't work you might have to build without Discord support (`make DISCORD_SDK=0`). I don't know if Discord is supposed to be supported on OSX.

**Comment by fgsfdsfgs** [comment]
Alright, try executing `gcc-11`. If it's present, compile with `make clean && make CC=gcc-11 CXX=g++-1`.

**Comment by NickHam13** [comment]
> 
> 
> Alright, try executing `gcc-11`. If it's present, compile with `make clean && make CC=gcc-11 CXX=g++-11 LD=gcc-11`.
> Or do `gcc-` and hit TAB and see what GCC you got installed, then use that version number.

I had to use gmake instead of make in the second command, but using these settings throws yet another error:
`src/pc/platform.c:86:10: fatal error: SDL2/SDL.h: No such file or directory`
`   86 | #include <SDL2/SDL.h>`
`      |          ^~~~~~~~~~~~`
`compilation terminated.`
`gmake: *** [Makefile:1082: build/us_pc/src/pc/platform.o] Error 1`

**Comment by NickHam13** [comment]
Fixed by https://github.com/djoslin0/sm64ex-coop/commit/8642479d82e438e705ad550462f13c6f716582fe.
