### ISSUE TITLE
When joining a server, the game chooses the color right after the color you picked.

### ISSUE THREAD

**Issue by mystic-akito** [djoslin0/sm64ex-coop#115]
**Describe the bug**
In Unstable 8, they allowed for you to change your color. When you join a server, however, it chooses the next color in the list, rather than the one you had chosen.

**To Reproduce**
1. Open game
2. Change Color
3. Join someone's game
4. Your color changes.

**Expected behavior**
When you join someone's game, you are supposed to be the color you have chosen. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Unstable 8

**Comment by djoslin0** [comment]
Are both players trying to use the same color? If that's the case it's the expected behavior.

**Comment by mystic-akito** [comment]
No, they weren't.

**Comment by djoslin0** [comment]
Should be fixed now
