### ISSUE TITLE
Unknown crash in CCM

### ISSUE THREAD

**Issue by somario360** [djoslin0/sm64ex-coop#12]
My friend (Mario) and I were collecting 8 Reds and 100-Coin in CCM when the game randomly stopped responding on my end. There was no error message at all. Screenshot is the frame of the crash.
![dwm_2020-09-01_14-43-00](https://user-images.githubusercontent.com/22121742/91898876-04d15800-ec62-11ea-9864-a7dd90d44e4f.jpg)

**Comment by djoslin0** [comment]
Hmm, this is going to be a really tough one. I tried to reproduce it but failed thus far. I really need to figure out a way to collect crash logs.

**Comment by djoslin0** [comment]
Upon further pondering, this sounds a lot like other issues I've experienced where the remote player's actions get caught in an infinite sequence. I've pushed a commit that should prevent the hang if this is the case, but I haven't fixed the underlying sequence. Next time you play, check for `%appdata%/Roaming/sm64ex/errorlog.txt` and send it to me if it exists.

**Comment by djoslin0** [comment]
closing as fixed, as I suspect it was an infinite loop of actions (which can't happen now)
