### ISSUE TITLE
Feature Request: Commands

### ISSUE THREAD

**Issue by IoIxD** [djoslin0/sm64ex-coop#120]
I think that it would be nice to have a command parser for at least one commands, especially for sessions when people are just screwing around: `/tp <player>` - probably the most important one. Something slightly annoying is when everybody is in a specific area in a specific level, and it takes awhile to get to the point, and by the time you get there they're done doing whatever they're doing. It'd be nice to be able to teleport to others.

`/list` might also be nice, and there's also a case to be made for an admin system and commands like `/kick` and `/ban`, but I don't know how players are actually coded so I'm not sure how much harder it would be to have them, and public servers won't be a thing until a headless server mode is added, so that can wait most likely.

**Comment by IsaacBrumby** [comment]
What would `/list` do?

**Comment by IoIxD** [comment]
`/list` would list all the players currently online. Admittedly not entirely useful but it feels like a given to implement.

**Comment by IsaacBrumby** [comment]
> `/list` would list all the players currently online. Admittedly not entirely useful but it feels like a given to implement.

ok well check this out

https://github.com/djoslin0/sm64ex-coop/pull/122

**Comment by djoslin0** [comment]
The following commands have been added: `/players`, `/kick`, `/ban`
Something like `/tp` will have to wait for the Lua API to get more mature. That's more in the realm of mods
