### ISSUE TITLE
Feature Request: Custom levels sent via the server

### ISSUE THREAD

**Issue by IoIxD** [djoslin0/sm64ex-coop#121]
I think custom levels are something that could really give the project a lot of uses outside of playing the base game with friends. Having level packs could allow for some very interesting play sessions as you could easily port levels from many ROM hacks into the format described below*, or you could just make your own levels to screw around with friends in.

Of course, one could recompile the game and change the levels to get this functionality, but I think it would be more efficient and user friendly if the server sent it. I don't know how hard this would be given the current code; there would need to be a special format because I don't think c files can be sent and dynamically used, but the format just needs to be a .zip file containing the obj or glTF file (preferably the latter since that can hold texture information), and a .yml file containing the initial object placements and the level information.

*even if there aren't PC ports already, I imagine that as long as the hack doesn't have too many custom objects or what not it wouldn't difficult to just rip the level model, convert it to the proper format, and populate the object list

**Comment by Beyley** [comment]
this likely will be impossible without rewriting level loading

**Comment by pjalsGit** [comment]
pretty sure what they proposed WAS rewriting level loading

**Comment by djoslin0** [comment]
Done

**Comment by IoIxD** [comment]
Hi, excuse my ignorance but I can't seem to find the explaination or anything on how to do this? Is it just an option built into the game?

**Comment by Beyley** [comment]
> Hi, excuse my ignorance but I can't seem to find the explaination or anything on how to do this? Is it just an option built into the game's menu, for the admin?

its seemless, it just does it
