### ISSUE TITLE
sm64ex-coop does not work properly with the Flatpak version of Discord

### ISSUE THREAD

**Issue by TGRush** [djoslin0/sm64ex-coop#123]
**Describe the bug**
Probably due to Flatpak's sandboxing, the sm64ex-coop executable seems to not be able to detect that Discord is even running in the first place 

Steps to reproduce:
1. Grab some Linux distro
2. Install Discord through Flatpak (Flathub.org if the repo isn't added yet)
3. Compile the game as normal
4. Run the game whilst Discord is running

**Expected behavior:**
Discord gives a dialog prompting for access as usual

**Screenshots:**
https://i.imgur.com/xYYFDcq.jpg

**Desktop (please complete the following information):**
 - OS: Fedora 35 running on KDE Plasma
 - Browser - Firefox (why is this needed?)
 - Version - 35, as mentioned before

**Additional context**
Do note that the game is running under XWayland instead of Native Wayland, though that likely won't make a difference

**Comment by djoslin0** [comment]
This cant be fixed on my end. Only the full Discord application provides the API.

**Comment by TGRush** [comment]
the flatpak variant is just a repackaged version of the official Discord client tho?

its not like Quarrel on Win10/11, its literally the full Discord client

**Comment by djoslin0** [comment]
In that case, flatpak's sandboxing is preventing Discord from communicating with the game.

> It is advertised as offering a sandbox environment in which users can run application software in isolation from the rest of the system. 

Unless I'm misunderstanding, the inability for Discord to communicate with sm64ex-coop is a feature of flatpak.

I'm unfamiliar with it, but the description sounds like it's working as designed.

**Comment by TGRush** [comment]
> Unless I'm misunderstanding, the inability for Discord to communicate with sm64ex-coop is a feature of flatpak.

Well yes, but actually no, you can grant any app permission to interact with other services and such on the host system, yet even upon doing that, it simply refuses
