### ISSUE TITLE
it won't compile 

### ISSUE THREAD

**Issue by Gibberditoslumber** [djoslin0/sm64ex-coop#124]
thare is no reproduce'ing it it just happens
**Expected behavior**
it compile's fine

**Screenshots**
https://user-images.githubusercontent.com/91945956/148710647-aa315093-782b-415b-aac9-ff329f4e4a40.png

 - OS Debian 11
 - Browser chrome
 - 22

**Comment by theclashingfritz** [comment]
Try running `make clean` then try again,

**Comment by Gibberditoslumber** [comment]
nope that didnt work

**Comment by djoslin0** [comment]
I this still an issue on the latest version? (unstable 13)

**Comment by Gibberditoslumber** [comment]
no i will deletd it
