### ISSUE TITLE
Dire Dire Docks missing red coin poles and one wall is solid even with invis cap when it shouldn't be

### ISSUE THREAD

**Issue by Melechtna** [djoslin0/sm64ex-coop#127]
**Describe the bug**
Description says it all. The wall in question is the left one if facing them from Bowsers Sub.

**To Reproduce**
1. Go to Dire Dire Docks Red Coin Poles
2. Get Invis cap
3. jump at left wall from sub
4. Hit wall and not be able to get through and the poles are missing

**Expected behavior**
The opposite of step 4

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Unstable 15

**Comment by fgsfdsfgs** [comment]
Don't these only appear after beating Bowser 1 or something? I remember this being brought up for the other ports.

**Comment by Melechtna** [comment]
> Don't these only appear after beating Bowser 1 or something? I remember this being brought up for the other ports.

I'd beaten the first bowser. The "run" was glitchless with a friend.

**Comment by fgsfdsfgs** [comment]
Oh, it might even be Bowser 2. Check [this page](https://www.mariowiki.com/Pole-Jumping_for_Red_Coins).

**Comment by Melechtna** [comment]
> Oh, it might even be Bowser 2. Check [this page](https://www.mariowiki.com/Pole-Jumping_for_Red_Coins).

So it's a bug from the original game. Still not sure if the wall on the left is meant to still be solid when the invis cap is on, given the wall on the right isn't, because you can still technically complete it if it weren't for that.

**Comment by djoslin0** [comment]
It's a non-game breaking bug from the original game, won't fix
