### ISSUE TITLE
Trying to cross compile weirdness

### ISSUE THREAD

**Issue by Melechtna** [djoslin0/sm64ex-coop#129]
**Describe the bug**
With all the relevant mingw-w64 packages installed, claims winsock2.h doesn't exist when it does.

**To Reproduce**
run make WINDOWS_BUILD=1

**Expected behavior**
Compiles like normal

**Desktop (please complete the following information):**
 - OS: Arch
 - unstable 15

**Additional context**
The winsock2 files are in the mingw-w64-headers package, which I have installed, and the files exist in the system. No amount of fenegalling seems to get it to behave normally, either it introduces new errors, or just winds up right back with the "winsock2.h: No such file or directory" error, and copying the file into the source doesn't yield any results.

**Comment by Beyley** [comment]
If you read the wiki, its actually not possible to cross compile linux -> windows

**Comment by Melechtna** [comment]
> If you read the wiki, its actually not possible to cross compile linux -> windows https://github.com/djoslin0/sm64ex-coop/wiki/Compiling-on-Linux

Why don't you read it? It's talking about WSL, not Linux itself, otherwise explain the "WINDOWS_BUILD" flag.

**Comment by Beyley** [comment]
> > If you read the wiki, its actually not possible to cross compile linux -> windows https://github.com/djoslin0/sm64ex-coop/wiki/Compiling-on-Linux
> 
> Why don't you read it? It's talking about WSL, not Linux itself, otherwise explain the "WINDOWS_BUILD" flag.

It says WSL ***or*** Linux, so right back atcha, and anyway, the build flag is there itself beacuse MSYS bs, it SHOULD be autoset by the makefile, see [here](https://github.com/djoslin0/sm64ex-coop/blob/fc8bb5e6bdf44369877c1e8e62f46023b868189c/Makefile#L99) but in the rare case it isnt, you can override and force a windows build incase the makefile incorrectly assumes your OS as non-windows during a windows build
