### ISSUE TITLE
Cant join the online rooms

### ISSUE THREAD

**Issue by IamNotDoneYET** [djoslin0/sm64ex-coop#139]
When I am trying to join a game, it's looking like it's joining but it's not joining.[https://cdn.discordapp.com/attachments/926852328479416320/947529393671114792/Screenshot_2.png](url)

**Comment by SonicDarkYT** [comment]
when this happened to me, i just turned off the pc and then turned on, it should be fixed with that

**Comment by IamNotDoneYET** [comment]
> 

But I tired it like +100 times

**Comment by djoslin0** [comment]
restart discord and have the game open when you click join on an invite
