### ISSUE TITLE
Dynes broke Mac support

### ISSUE THREAD

**Issue by EmeraldLoc** [djoslin0/sm64ex-coop#141]
Ok, so everything was working great until v20 when DynOS support got merged to unstable. This is a request to add a branch for macOS to remove DynOS.

**Comment by djoslin0** [comment]
DynOS will become a critical feature for Lua mods in the future. A compile flag to remove DynOS would only be a temporary fix. I'll try to figure out how to fix it in Mac builds

**Comment by djoslin0** [comment]
Should be fixed now, close this issue if that's true

**Comment by EmeraldLoc** [comment]
Wow, it worked. Thanks a lot!
