### ISSUE TITLE
Doesn't link with 'make DISCORDRPC=0 DISCORD_SDK=0'

### ISSUE THREAD

**Issue by MGislv** [djoslin0/sm64ex-coop#142]
**Describe the bug**
When compiling with `make DISCORDRPC=0 DISCORD_SDK=0`, `ld` fails:
`ld: unrecognised emulation mode: arch=native
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu elf_l1om elf_k1om i386pep i386pe
make: *** [Makefile:1205: build/us_pc/sm64.us.f3dex2e] Error 1`

**To Reproduce**
1. Compile with `make DISCORDRPC=0 DISCORD_SDK=0`
2. Error when linking

**Expected behavior**
Should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux arch 5.16.14-arch1-1 (glibc)

**Additional context**
Works if #91 is applied, probably the same issue as #111.

**Comment by djoslin0** [comment]
Fixed
