### ISSUE TITLE
Mad piano causes game crash in split screen local co-op

### ISSUE THREAD

**Issue by jp615** [djoslin0/sm64ex-coop#145]
**Describe the bug**
The game crashes while in Big Boo's stage whenever the mad piano moves/attacks.  The game doesn't crash **until** mad piano actually moves/attacks.  It has something to do with his actual attack.  I am playing split screen local coop on Nucleus coop, the newest update v2.0.  I don't know if it has anything to do with that or not but those are my playing conditions.  I can't get all 8 red coins on this stage as a consequence of this problem.

**To Reproduce**
1. Go to - 'Big Boo's stage.  Go to the room with mad piano.  Get close enough so that mad piano attacks.

**Expected behavior**
Game will crash when mad piano starts attacking.

**Desktop**
 - OS: [Win 7 Pro x64]

**Comment by djoslin0** [comment]
It sounds like you're running Beta 2. That version is ancient. This bug was fixed a long time ago in the `unstable` branch (the only branch that exists anymore)

**Comment by jp615** [comment]
I'm not exactly sure what you're talking about to be honest.  I just know that I compiled the game about a month ago.  When I compiled there were 2 branches to choose from, "coop" and "unstable".  I used coop.  I don't remember seeing anything that said beta 2.  Should I recompile and choose "unstable"?

**Comment by Isaac0-dev** [comment]
yes, you should recompile with "unstable"

**Comment by jp615** [comment]
Ok.  What do I do about the save data that I have on the current recompile?  Will it erase?  Is there a way to make a backup or transfer to the new version?

**Comment by Isaac0-dev** [comment]
your save data will carry over to the new version

**Comment by jp615** [comment]
Ok thanks.  And just out of curiosity, where exactly is the save data located anyways?  Just in case I need to make a future backup

**Comment by Isaac0-dev** [comment]
On Windows, its in %appdata%/sm64ex-coop.
The save file itself is called sm64_save_file.bin
The folder also contains other things that the game uses.

**Comment by jp615** [comment]
man I'm sorry to clog up this board, I hope I'm not, but I just got an error recompiling.  I'm not sure what went wrong or what to do.  Where do I need to go for help?

**Comment by Isaac0-dev** [comment]
Best place to go would be to go to the Discord server for this project. [https://discord.com/invite/TJVKHS4](url)
If you don't have a Discord account and aren't willing to make one, you can just put your log here.
Are you using msys2 by itself to compile, or are you using builder2? (If you don't know what one of them is, thats ok)
Its recommended for beginners to use a special tool that was created for this project.
[https://github.com/coop-compiler/coop-compiler/releases/latest/download/coop-compiler.exe](url)

**Comment by jp615** [comment]
I'm using the sm64pcbuilder2.  I made sure to clear the repo and us_pc, and reinstalled dependencies first.  Then I selected sm64ex-coop unstable, installed the render96HD textures, selected a couple of models 1 for Mario 1 for Luigi, selected extended moveset.  Did all that and hit compile.  I never got any errors the last time I compiled.  

Here's the log file
[BuilderLog_v1.17.4_sm64ex-coop-unstable_Failure_2022-03-25_02.28.50.txt](https://github.com/djoslin0/sm64ex-coop/files/8348577/BuilderLog_v1.17.4_sm64ex-coop-unstable_Failure_2022-03-25_02.28.50.txt)
.

**Comment by Isaac0-dev** [comment]
It looks like you are trying to use extended moveset, and other patches. 
Extended moveset is the patch that made the compilation fail, but I recommend not compiling with any patches because extended moveset comes as a lua script.

**Comment by jp615** [comment]
Ok what exactly does that mean?  I can still use it (the moveset), but I would just have to apply it another way?  And what about the render96 textures?  I can apply those safely right?

**Comment by Isaac0-dev** [comment]
Yeah the render96 textures should be able to stay there.
The latest version supports a type of mod that can run without recompiling.
There are some mods that come with the latest version, and extended moveset is one of them.
![image](https://user-images.githubusercontent.com/62234577/160082455-b8f59a97-5f6b-4307-9a35-6141202cc74d.png)

**Comment by jp615** [comment]
Where can I get those mods??

**Comment by Isaac0-dev** [comment]
They should come with the game.
Just open it, and click Host > Mods.
Look for Extended Moveset.

**Comment by Filipianosol** [comment]
I wanted to post this on Discord but I couldn't find you in the sm64ex-coop server.

Make sure to update Builder2 too, incompatible coop patches had since been removed, + there's some other new stuff:
https://sm64pc.info/sm64pcbuilder2/

**Comment by jp615** [comment]
Ok thanks for your help
