### ISSUE TITLE
Boo's Haunt

### ISSUE THREAD

**Issue by qazwsxedcrfv64** [djoslin0/sm64ex-coop#147]
https://cdn.discordapp.com/attachments/752687113593683968/962869671525244988/unknown.png

**Comment by Agent-11** [comment]
Which boo? The big boo? The small boo? Medium sized?

**Comment by Gibberditoslumber** [comment]
what

**Comment by EmeraldLoc** [comment]
I would close this, as you are not giving enough information, and it has been long enough

**Comment by djoslin0** [comment]
Closing as I think its fixed, feel free to reopen if that isnt the case
