### ISSUE TITLE
Analogue Camera Wing Cap

### ISSUE THREAD

**Issue by somario360** [djoslin0/sm64ex-coop#15]
When using the wing cap after a triple jump with the analogue camera option turned off, the camera will gradually get lower. This is especially noticeable on Tower of the Wing Cap.
![sm64 us f3dex2e_2020-09-03_12-55-03](https://user-images.githubusercontent.com/22121742/92151218-5f93bc80-ede6-11ea-959e-093da6a9a951.png)

**Comment by djoslin0** [comment]
As posted in the discord, the workaround right now is to call `make` like this: `make BETTERCAMERA=0`
I'll look into what is going on here.
