### ISSUE TITLE
Flatpak issue is solved on the discord flatpack's end

### ISSUE THREAD

**Issue by mariomadproductions** [djoslin0/sm64ex-coop#150]
https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)

just needs a slightly different implementation on the app's end

related issues:
https://github.com/djoslin0/sm64ex-coop/issues/123
https://github.com/djoslin0/sm64ex-coop/issues/144

**Comment by mjcox244** [comment]
This isn't for the app to do, this is for the user to run.

Use the non sandbox guide

**Comment by Beyley** [comment]
> https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)
> 
> just needs a slightly different implementation on the app's end
> 
> related issues: #123 #144

issue still not on our side lmao, someone should prob close this, and put that link in discord #faqs

**Comment by mariomadproductions** [comment]
ah right good point, i misread it. yeah seems a simple enough thing on the users end.
