### ISSUE TITLE
--Nvm--

### ISSUE THREAD

**Issue by KajeArch** [djoslin0/sm64ex-coop#151]
--Nvm--
EDIT: I failed to understand how HOOK_ON_PLAYER_CONNECTED actually works. I assumed that it would callback for the player that just connected. That isn't the case as I assumed earlier because the hook is locally calling for all the players with exception of the player that joined. So this issue can be closed.

**Comment by Amy54Desu** [comment]
Yeah, no matter what I did it always failed to send the message. The first player (aka the Host) would receive the message fine, originally I assumed it was a problem with the chat_box, but after using print and realizing it didn't print anything at all that's when I realized something was wrong
