### ISSUE TITLE
Shifting Sand Lands Red Coins are lost if player 1 is in pyramid and player 2 collects coins and leaves

### ISSUE THREAD

**Issue by HunterHeard** [djoslin0/sm64ex-coop#153]
**Describe the bug**
If one player is in the Pyramid and the other is outside collecting red coins then dies, those red coins are lost; when that player comes back and enters the same star, they start off without those red coins but those red coins are also still gone from the stage. This bug also occurs for any level with red coins and multiple areas (Cool Cool Mountain, Snow Man's Land, etc). It's also probably the case for secrets as well.

**To Reproduce**
1. Start a game with 2 players
2. Have both of them go to Shifting Sand Land, choose the same star
3. Have one player enter the Pyramid (Let's call this one Luigi)
4. Have Mario grab a red coin (At this point, pause with Luigi and you can see he doesn't get the red coin, though he does get the 2 coins)
5. Have Mario exit the stage (by dying or whatever)
6. Have Mario re-enter the stage, and choose the same star
7. Try to collect the rest of the 8 red coins, you will notice that you start with none even though the ones you collected are gone from the stage

**Expected behavior**
At step 4, (image 2) Luigi should be able to see the red coin when he pauses.
At step 7, (image 3) Mario should be able to see the red coins he collected before dying when he pauses, and when he collects another red coin the number should start where he left off, not at "1".

**Screenshots**
Mario having grabbed the first red coin
![Mario having grabbed the first red coin](https://user-images.githubusercontent.com/17091922/167227367-9afc5e04-649e-49b1-bdc0-4e6e492b2954.png)
Luigi with 2 coins but no red coin
![Luigi with 2 coins but no red coin](https://user-images.githubusercontent.com/17091922/167227253-be5497a9-1ff1-4764-8e0b-6d123497555e.png)
Mario having exited and re-entered the stage to find no red coin in the stage or his inventory
![M2](https://user-images.githubusercontent.com/17091922/167227392-45354f8b-c177-4584-b8b8-1414f1b2db30.png)

 - OS: Windows 10

**Comment by Amy54Desu** [comment]
Odd that the game just nuked the red coin and didn't respawn it

**Comment by HunterHeard** [comment]
> Odd that the game just nuked the red coin and didn't respawn it

As long as Luigi is in Shifting Sand Land, the game is keeping a "session" going. The things on the map that get destroyed (enemies, coins, etc) are retained. The one issue here is the red coin didn't make it into Luigi's inventory somehow, so it's just gone.

**Comment by HunterHeard** [comment]
I was able to fix it by changing packet_collect_coin.c
I'll post later

**Comment by HunterHeard** [comment]
https://github.com/djoslin0/sm64ex-coop/pull/154

**Comment by djoslin0** [comment]
fixed
