### ISSUE TITLE
Not being able to use HD skyboxes (Render96) with sm64coop

### ISSUE THREAD

**Issue by Gagert** [djoslin0/sm64ex-coop#158]
**Describe the bug**
After compiling sm64coop with sm64pcBuilder2, I had to manually download the Render96 HD textures pack and move the downloaded folder inside the dynos folder of sm64coop (the built-in function in sm64pcBuilder2 to apply the Render96 HD texture pack didn't work as intended) for making the HD textures work with sm64coop.

The only issue then was that all the skyboxes in-game was still low res.

**To Reproduce**
Install the Render96 HD texture pack to the dynos folder in sm64coop, and watch all HD textures besides the HD skyboxes working as intended.

**Expected behavior**
I expected the HD skyboxes to work since all the HD textures did so.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: FireFox
 - Version: build 91ee4f8 of sm64coop

**Comment by Agent-11** [comment]
skybox textures are split into 64 pieces when compiling, dragging 1 big map of those isn't going to work.

**Comment by Gagert** [comment]
I somehow managed to fix this now. I don't know exactly what I did that fixed this issue, but I recompiled sm64coop while having reorganized a couple of folders inside of sm64pcBuilder2.

**Comment by Agent-11** [comment]
kk

**Comment by Gagert** [comment]
I discovered that there's now a folder within the compiled us_pc folder named res, and within the res-folder there's a zip-file called "render96_hd_sm64ex-and-others.zip". If I remove this zip file, all the HD skyboxes and HD textures disappear. There's also a base.zip file here (I'll just write all this here for future references). I no longer have any need for the HD textures to be within the dynos-folder, where the player models are.
