### ISSUE TITLE
Crash when pausing the game (Win 8.1)

### ISSUE THREAD

**Issue by paperlyly** [djoslin0/sm64ex-coop#159]
when playing at any level, and pausing a few times the cuego stays hanging, and it becomes necessary to close it suddenly
it only happens on my friend's computer, use windows 8.1, already try to play it on mine, which has linux and does not succeed

**Comment by Bloxxel64** [comment]
> when playing at any level, and pausing a few times the cuego stays hanging, and it becomes necessary to close it suddenly it only happens on my friend's computer, use windows 8.1, already try to play it on mine, which has linux and does not succeed

i can help with linux

**Comment by paperlyly** [comment]
what should I do in linux if that happens?

**Comment by paperlyly** [comment]
> > when playing at any level, and pausing a few times the cuego stays hanging, and it becomes necessary to close it suddenly it only happens on my friend's computer, use windows 8.1, already try to play it on mine, which has linux and does not succeed
> 
> i can help with linux

what should I do in linux if that happens?

**Comment by djoslin0** [comment]
Fixed
