### ISSUE TITLE
Sm74 loading when it shouldnt 

### ISSUE THREAD

**Issue by Blockyyy** [djoslin0/sm64ex-coop#160]
**Describe the bug**
Every time i want to host a game and the mario 74 mod is in my folder when trying to host base game it tries to load 74 without levels for example it spawns OTHERS in the courtyard at the beggining but not me and when hosting with mods like hns it appears for me but not the others they also have a /swap command

I have an idea of what could have caused this but i am not sure

**To Reproduce**
So i had a mod i made that added levels but since i was bored i took the levels from 74 put them in levels folder and took the /swap command  it asked me to replace i said yes i had fun exploring the mess i created and then stopped hosting and thats pretty much it

**Expected behavior**
Didnt expect anything other then just disabling the mod and playing like normal

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version unst28.1

**Comment by djoslin0** [comment]
Does this still happen?

**Comment by Agent-11** [comment]
I'm pretty sure this was like right around when mod cache started being implemented or at least the early days of it. I highly doubt this still happens
