### ISSUE TITLE
Snowman Land Bug

### ISSUE THREAD

**Issue by Xboxy** [djoslin0/sm64ex-coop#163]
**Expected behavior**
https://user-images.githubusercontent.com/104048248/180519932-1b889c8c-373a-4043-bb99-d982e0a0ff8f.png

**Desktop (please complete the following information):**
 - Latest Version
- OpenGL

**Additional context**
This happens with many players

**Comment by Agent-11** [comment]
Totally never seen this bug before ever, although I'm not surprised since this is coming a from a 9 year banned from almost every sm64 server and even a certain Mario vs Luigi server too

**Comment by Agent-11** [comment]
Duplicate, fixed
