### ISSUE TITLE
Snow Slides Bug when playing more than 2 players - Snowman's Land

### ISSUE THREAD

**Issue by AdrianCarmonaRoda** [djoslin0/sm64ex-coop#167]
Steps to reproduce:

1. Enter Snowman's Land with a minimum of three players
2. Go to the Snow slides
3. They start appearing in greater rate

![imagen](https://user-images.githubusercontent.com/42941048/185718141-215263bb-7db5-4d4b-bf2d-9d2aa81eebe4.png)

S.O: Windows 11 - 64 bits
CPU: Intel Core I9-12
GPU: NVidia RTX 3070 ti
sm64ex-coop Version: beta 29.0

**Comment by Amy54Desu** [comment]
This is an already known bug, due to both players claiming ownership over the spawner, this is not only in Beta 29 as it has existed in previous versions

**Comment by djoslin0** [comment]
fixed
