### ISSUE TITLE
Suggestion: ChromeOS/Chromebook support? (This is gonna make me sound insane.)

### ISSUE THREAD

**Issue by BluCoolKnux** [djoslin0/sm64ex-coop#169]
Alright so, I've heard that this game/mod is supported on Windows, Mac, and Linux, but a few of my friends on Discord don't have **either** of those. They **do** have Chromebooks, but I don't think ChromeOS can run this game. So, what if that could be turned around in some way? Either through a different build, or a different way of installation/compiling, or some other technicality, I can imagine it'll work just as well as the other versions/builds, even if performance varies. I bet this entire thing makes me sound insane, but I'm spawning this idea for everyone who has ChromeOS. What do you all think? Am I insane? Am I a genius? I'm not sure at this point.

**Comment by Agent-11** [comment]
Just use the Linux feature on ChromeOS or whatever

**Comment by WryOpussum** [comment]
Try using this https://support.google.com/chromebook/answer/9145439?hl=en

**Comment by tek967** [comment]
yep, just use the linux feature on chromebooks.
