### ISSUE TITLE
Munching Piano Crash (BBH)

### ISSUE THREAD

**Issue by anuserlol** [djoslin0/sm64ex-coop#17]
If Mario (Host) triggers the piano to attack him before Luigi (Player 2) sees it, Luigi's game will crash with no error window.

**To Reproduce**
1. Go to Big Boo's Haunt [MAKE SURE PLAYER 2 IS HAS NOT LOADED THE PIANO YET, he should be in another room]
2. Go to the piano's room and trigger it as Mario
3. The other player's game will crash

![imagen](https://user-images.githubusercontent.com/16540103/92153552-c1731700-ee24-11ea-8f14-22c81ffdec08.png)
_Screenshot taken as soon as the other player crashed, just for context._

**Comment by djoslin0** [comment]
Hmm, I haven't been able to reproduce this. Is there any step that I might be missing?

**Comment by djoslin0** [comment]
this may be fixed, I changed how a room is determined as 'active'

**Comment by djoslin0** [comment]
closing as fixed unless it appears again
