### ISSUE TITLE
Suggestion: Lua hook for sent chat messages.

### ISSUE THREAD

**Issue by IoIxD** [djoslin0/sm64ex-coop#174]
I plan on hosting a 24/7 server for me and friends and I'd like to have a bridge between the server and our Discord chat. This would be possible if there were Lua hooks for chat messages.

I'm capable of doing this myself and will  create a PR adding this if nobody does it before me.

**Comment by Isaac0-dev** [comment]
huh? hooks for chat messages do exist
[`hook_chat_command`](https://github.com/djoslin0/sm64ex-coop/blob/coop/docs/lua/guides/hooks.md#hook_chat_command)
also if you're hoping to use the headless server you can make other players "moderators" so you can use some functionality that is only available from the server, but from the client instead

**Comment by IoIxD** [comment]
All chat messages, not just commands.

**Comment by Isaac0-dev** [comment]
what do you want to do with that? it sounds to me like you're trying to do something thats better done in C

**Comment by IoIxD** [comment]
I would like a channel where chat messages and events are logged.

This seems very questionable/suspicious when I type it out but this is something that me and my friends have agreed to (when its possible) for any of the private online servers we play on.

![image](https://user-images.githubusercontent.com/30945097/198200113-994a25d3-f2d8-446a-84fd-a8546bcd459b.png)
![image](https://user-images.githubusercontent.com/30945097/198200234-06842a58-687e-412d-a6e4-d7766944f2e1.png)

**Comment by Isaac0-dev** [comment]
well its possible to recreate most event checks that you want with Lua. For example there are already hooks for players connecting/disconnecting, you can check what level you are in, so when your level changes, send a message to the server through the global sync table or something like that. its also possible to check how many players are connected at once.
I don't think you need a hook to know when those events occur.
by the way we have a Discord, you may find it useful to talk about this there. https://discord.gg/eXhpSRhCyM

**Comment by IoIxD** [comment]
Those are all good but the messages are the most important part here. It's not only about having an archive of the events but being able to communicate with people online without logging in.

I'm already in the Discord, actually. I forgot I was before opening the issue.

**Comment by Isaac0-dev** [comment]
oh if you want to send messages from a discord bot to the server, you can use `djui_chat_message_create` to make a fake chat message
how you would get the message from the discord bot to the server i don't know but I assume when you came up with this idea you knew how to do that with Lua.

**Comment by IoIxD** [comment]
Yes, I can do that. But I want to send messages from the server to Discord as well.

**Comment by Isaac0-dev** [comment]
ahh now i see what you mean. as far as i am aware there is no way to see the chat message history through Lua, so if you want to make a pr for it you are welcome, but otherwise I will personally add it if you don't.

**Comment by IoIxD** [comment]
:+1: I will probably take a week or two to get to this so if you can do it faster then me that would be appreciated (and it would also be appreciated because I'm not quite sure if I've found where this would go, and you're more familiar with the code base then me).

**Comment by Isaac0-dev** [comment]
alright i have added the hook and it will be available next update. it will be called `HOOK_ON_CHAT_MESSAGE`, and it will have the mario state of the player that sent the message, the message string itself, and you can return false to prevent the message from showing in chat (I did this so people might be able to make chat filters or something like that)
