### ISSUE TITLE
cap glitch

### ISSUE THREAD

**Issue by DanielGames2932** [djoslin0/sm64ex-coop#175]
when you lose your cap in a level like SSL or SL and then you leave the level without getting your hat back, the hat just goes back to you when you get out of the painting

**Comment by Agent-11** [comment]
This is intended for developer's sanity so we don't have to try to network caps and saving and all of that

**Comment by Hri7566** [comment]
lazy

**Comment by Agent-11** [comment]
> lazy

prs are open 👍
