### ISSUE TITLE
Can't join an open group

### ISSUE THREAD

**Issue by BluCoolKnux** [djoslin0/sm64ex-coop#178]
Whenever I join an open group from a Discord invite, the app takes me to the "Joining" screen, but it stays there and doesn't let me into the game that the person is hosting.

1. Go to a game invite
2. Click on 'Join'
3. See error

The game should take you to the "Joining" screen, but it may not let you into the game you were invited to.

![image](https://user-images.githubusercontent.com/63269642/202872550-a2036a5a-0773-4aac-a7a4-5a5d3830a3d2.png)

**Desktop:**
 - OS: Windows 11
 - Using the app built by the coop-compiler
 - Version 30

**Comment by Agent-11** [comment]
It's a problem with DIscord's side right now, we don't know if it's going to be fixed but if not we're working on a new system that doesn't use discord's now deprecated game SDK

**Comment by ravillarreal** [comment]
And with direct connect? i tried connecting yesterday with my friend trough my public ip, with radmin VPN and nothing it keeps connecting like the image :( any help?

**Comment by PlayerFridei** [comment]
I'm having the same issue too! I can't even **INVITE** tru discord! **(when hosting my own game)**

- Version Beta 30.0
- OS: Windows 10

**Comment by stvene3004** [comment]
Bruh they already told ya that ya can't invite through Discord right now.

**Comment by PlayerFridei** [comment]
> Bruh they already told ya that ya can't invite through Discord right now.

My friend was able to invite me but it didn't let me join his game, but when I tried to host and invite my friend, it doesn't let me invite, invite button was not even visible on discord, how my friend was able to then? Whaaat? 

And portforwarding with my router is pain... hopefully they come up with a solution 👍

**Comment by DJCPT** [comment]
I can't join and my friend can't join me with Discord invites, port forwarding, or hamachi/radmin. What's the issue?

**Comment by stvene3004** [comment]
> I can't join and my friend can't join me with Discord invites, port forwarding, or hamachi/radmin. What's the issue?

Now first of all, how are you guys doin' the Direct Connection method? I'm pretty sure y'all messed somethin' up here

**Comment by djoslin0** [comment]
Discord fixed their API... for now
