### ISSUE TITLE
can't join servvers.

### ISSUE THREAD

**Issue by Southinverted** [djoslin0/sm64ex-coop#181]
**Describe the bug**
ive tried joining and hosting through discord, and using portforwarding and hamachi. I'm still not able to join servers or have other people join mine.

**To Reproduce**
Join a server in literally any way. 

**Expected behavior**
You will be stuck on the loading screen.

**Desktop (please complete the following information):**
Windows
version 30

**Additional context**

I've not been able to join or host servers, and neither has my friend been able to.

**Comment by CJRed1** [comment]
Discord fucked up the invite system, the only solution we have right now is via Radmin VPN

**Comment by djoslin0** [comment]
Discord fixed their API... for now

**Comment by Terrance** [comment]
> Discord fixed their API... for now

I'm guessing from the timing that I started playing shortly after it started working, but now it's broken again -- after a few sessions with friends, I'm now (as of 10th May) unable to invite them through Discord.

In Discord's developer tools, I can see the invite message failing to send:

```json
{"message": "Invalid Activity Action", "code": 50039}
```
