### ISSUE TITLE
Creation of synced objects via Lua cannot be guaranteed

### ISSUE THREAD

**Issue by siege918** [djoslin0/sm64ex-coop#186]
**Describe the bug**
Creating objects via `spawn_sync_object` occasionally fails silently, with no way to ensure that the object gets created.

**To Reproduce**
1. Add the following mod behavior:
```
function fling_coin(coin)
    print("coin flung")
    coin.oForwardVel = math.random() * 20
    coin.oVelY = math.random() * 40 + 20
    coin.oMoveAngleYaw = math.random(0, 65535)
end

function obj_spawn_yellow_coins_synced(obj, numCoins)
    for i=1,numCoins do
        print("spawning coin")
        local coin = spawn_sync_object(id_bhvMovingYellowCoin, E_MODEL_YELLOW_COIN, obj.oPosX, obj.oPosY, obj.oPosZ, fling_coin)
    end
end

hook_event(HOOK_ON_PVP_ATTACK, function(a, v) 
    obj_spawn_yellow_coins_synced(v.marioObj, 10)
end)
```
2. Connect to a multiplayer game with two players
3. Have one player punch the other 3 times
4. Less than 30 total coins are spawned, "spawning coin" is printed 30 times, and "coin flung" is printed to the console less than 30 times

**Expected behavior**
Thirty total coins are created, their movement is synced between all players, and both print statements print 30 times each

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Beta 30

**Additional context**
I would expect there to be some way to guarantee the creation of a synced object, even if it isn't instantaneous. I have yet to find a workaround for this.

If this isn't possible, I would want some kind of logging when creation of an object fails and the reason for its failure.

**Comment by djoslin0** [comment]
You can check the return value of spawn_sync_object, if it's `nil` then it failed to spawn.
The amount of sync objects that can be created will be massively increased in beta 33. It still won't be guaranteed, but I've seen hundreds of sync objects on the new version.
