### ISSUE TITLE
How do I open sm64ex-coop?

### ISSUE THREAD

**Issue by NotZaky4** [djoslin0/sm64ex-coop#188]
After compiling with the coop-compiler, I opened the game from there. After configuring some settings and testing, I closed the game. But now I don't know how to open it again. I found an sm64ex-coop folder in my Roaming folder, but it doesn't have an .exe or anything like that.

**Comment by Yoshi549** [comment]
Check for a folder named "bin" where coop-compiler.exe is, there should be an program named "sm64.us.f3dex2e.exe", run it and make a shortcut on your desktop so you dont run it from there
