### ISSUE TITLE
Binutils 2.40 on Arch: Error linking final executable because of libbass local symbols

### ISSUE THREAD

**Issue by someone2639** [djoslin0/sm64ex-coop#189]
**Describe the bug**
When linking the final sm64.us.f3dex2e, `ld` cannot parse the local symbols in `libbass.so` and `libbass_fx.so` and fails. This is reminiscent of a bug in binutils 2.36 for the `mips-linux-gnu-` target where incorrectly organized ELF files built from IRIX based systems would fail to link on a modern system if they included local symbols.

**To Reproduce**
Using binutils 2.40:
- Clone the repository on the `coop` branch
- run `make` to completion 

**Screenshots**
```
Linking executable: build/us_pc/sm64.us.f3dex2e
/usr/bin/ld: build/us_pc/libbass.so: .dynsym local symbol at index 2 (>= sh_info of 2)
/usr/bin/ld: build/us_pc/libbass.so: .dynsym local symbol at index 3 (>= sh_info of 2)
/usr/bin/ld: build/us_pc/libbass.so: .dynsym local symbol at index 4 (>= sh_info of 2)
/usr/bin/ld: build/us_pc/libbass_fx.so: .dynsym local symbol at index 2 (>= sh_info of 2)
/usr/bin/ld: build/us_pc/libbass_fx.so: .dynsym local symbol at index 3 (>= sh_info of 2)
/usr/bin/ld: build/us_pc/libbass_fx.so: .dynsym local symbol at index 4 (>= sh_info of 2)
```
```
$ objdump -t lib/bass/libbass.so 

lib/bass/libbass.so:     file format elf64-x86-64

SYMBOL TABLE:
no symbols
```

**Desktop (please complete the following information):**
OS: Arch Linux x86_64
Kernel: 6.1.9-arch1-1

**Comment by Agent-11** [comment]
Sorry about that, bass is a library sm64ex-coop uses for mp3/ogg audio in Lua mods but it has been overall very problematic and honestly poorly implemented. I've been wanting to swap it out with a better audio library for a while now but just haven't gotten to it.

**Comment by willsherwood** [comment]
Same error on Ubuntu 64 bits. Can't play

**Comment by djoslin0** [comment]
While I don't fully understand the warning messages, it still links and produces a working build for me.
Does it produce a working executable for you?

**Comment by someone2639** [comment]
i might be stupid (the exe does build and work, and those were indeed warnings, i just tunnel visioned since the last line wasnt a success :disappointed_relieved:)

**Comment by djoslin0** [comment]
Yeah I'm hoping we can swap out bass with something else eventually. For the meantime I just ignore the warning heh
