### ISSUE TITLE
Mac won't start game

### ISSUE THREAD

**Issue by Treehopper54** [djoslin0/sm64ex-coop#197]
So I am using a mac intel, and after I do all of the steps in my terminal, when I enter the "./build/us_pc/sm64.us.f3dex2e" command, it produces an error saying "zsh: no such file or directory: ./build/us_pc/sm64.us.f3dex2e" I have no idea on how to reproduce this on other macs, since i only own one, yet this happens for me every time I try. I do not know what do to do, is there any known solutions for this?

**Comment by EmeraldLoc** [comment]
Sounds like it failed to compile, please provide the compilation logs.

**Comment by Treehopper54** [comment]
what

**Comment by Treehopper54** [comment]
the issue has been resolved, i had to add ".app" at the end of the final line of code needed to play and wiki edits should be made to fix this

**Comment by Treehopper54** [comment]
i forgot to close this
