### ISSUE TITLE
Crash handles doesn't work on Pop!_OS (And probably other Ubuntu-based distros aswell)

### ISSUE THREAD

**Issue by SCharryaB3** [djoslin0/sm64ex-coop#199]
The crash-handler doesn't work on Pop!_OS (I dont know about other Linux distros, but they might have the same problem)

**To Reproduce**
Just crash the game

**Expected behavior**
It should show the crash-handles, instead it just closes the game.

**Desktop**
 - OS: Linux (Pop!_OS)

**Comment by Isaac0-dev** [comment]
the crash handler doesn't work on anything other than windows
its not planned to make it work on anything else either, but if you know of an easy way to handle crashes we would be interested

**Comment by Isaac0-dev** [comment]
> its not planned to make it work on anything else either, but if you know of an easy way to handle crashes on linux we would be interested

I take that back, I found out how crash handling is done on linux. here's a sneek peek of the crash screen on linux (looks basically the same)
![](https://cdn.discordapp.com/attachments/1071559904101400666/1099928872084045905/image.png)
