### ISSUE TITLE
Crash on CCM slide

### ISSUE THREAD

**Issue by somario360** [djoslin0/sm64ex-coop#2]
After I (Luigi) exited the slide in CCM, an error message appeared and ignoring would make it pop up again.
![sm64 us f3dex2e_2020-08-30_14-02-40](https://user-images.githubusercontent.com/22121742/91667377-d0c32f00-eac9-11ea-957d-3d682c586ff3.png)

**Comment by djoslin0** [comment]
Thanks for the bug report!
I believe this is now fixed.

**Comment by djoslin0** [comment]
Let me know if this should be reopened.
