### ISSUE TITLE
Cant compile the game (sdl2-config not found)

### ISSUE THREAD

**Issue by Kingscur** [djoslin0/sm64ex-coop#215]
I cant compile the game 

1. Follow the Wiki on how to compile for linux
2. compile it with "make -j4"

Building Game...
Makefile:1268: warning: overriding recipe for target 'build/us_pc/'
Makefile:1259: warning: ignoring old recipe for target 'build/us_pc/'
Compiling: src/engine/behavior_script.c -> build/us_pc/src/engine/behavior_script.o
Compiling: src/engine/geo_layout.c -> build/us_pc/src/engine/geo_layout.o
Compiling: src/engine/graph_node.c -> build/us_pc/src/engine/graph_node.o
Compiling: src/engine/graph_node_manager.c -> build/us_pc/src/engine/graph_node_manager.o
/bin/sh: line 1: sdl2-config: command not found
/bin/sh: line 1: sdl2-config: command not found
/bin/sh: line 1: sdl2-config: command not found
/bin/sh: line 1: sdl2-config: command not found
In file included from ./data/dynos.c.h:5,
                 from include/types.h:441,
                 from src/engine/graph_node_manager.c:3:
./data/dynos.h:14:10: fatal error: SDL2/SDL.h: No such file or directory
   14 | #include <SDL2/SDL.h>
      |          ^~~~~~~~~~~~
compilation terminated.
In file included from ./data/dynos.c.h:5,
                 from include/types.h:441,
                 from include/sm64.h:6,
                 from src/engine/behavior_script.c:3:
./data/dynos.h:14:10: fatal error: SDL2/SDL.h: No such file or directory
   14 | #include <SDL2/SDL.h>
      |          ^~~~~~~~~~~~
compilation terminated.
In file included from ./data/dynos.c.h:5,
                 from include/types.h:441,
                 from include/sm64.h:6,
                 from src/engine/geo_layout.c:2:
./data/dynos.h:14:10: fatal error: SDL2/SDL.h: No such file or directory
   14 | #include <SDL2/SDL.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1532: build/us_pc/src/engine/graph_node_manager.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:1532: build/us_pc/src/engine/behavior_script.o] Error 1
In file included from ./data/dynos.c.h:5,
                 from include/types.h:441,
                 from include/sm64.h:6,
                 from src/engine/graph_node.c:2:
./data/dynos.h:14:10: fatal error: SDL2/SDL.h: No such file or directory
   14 | #include <SDL2/SDL.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1532: build/us_pc/src/engine/geo_layout.o] Error 1
make: *** [Makefile:1532: build/us_pc/src/engine/graph_node.o] Error 1

 - OS: Linux Nobara 37 (Fedora), 64bit, Kernel 6.3.7-200.fsync.fc37.x86

**Comment by mr-sihc** [comment]
well obviously you didnt install SDL2 and its development files

**Comment by Kingscur** [comment]
Thank you, it worked
I thougt i installed them already, but it failed because libz-dev isnt in the fedora repos

**Comment by mr-sihc** [comment]
:+1:
