### ISSUE TITLE
Wrong Mario Model in EU version

### ISSUE THREAD

**Issue by mr-sihc** [djoslin0/sm64ex-coop#218]
**BUG**
marios SLIM IN EU!!!
what?

sorry for so many bugs, but i found this all and wanted to report all

** LEFT US | RIGHT EU **
![grafik](https://github.com/djoslin0/sm64ex-coop/assets/85245131/de2d3d24-0c5a-4be3-b9b8-e77e149a1ff0)

** EU IN EMULATOR **
![grafik](https://github.com/djoslin0/sm64ex-coop/assets/85245131/4ee2882e-f76d-48d0-b44d-6787213c145e)

the emulator screenshot isnt the clearest but in emulator you can see it like US really

it looks like luigi model

**Comment by EmeraldLoc** [comment]
Thanks for reporting the bugs, not enough ppl do. Just wondering to ensure it isn’t normal in the eu version, on your emulator, make sure aspect ratio is normal aspect ratio for n64 and your not using widescreen stretched.

**Comment by Isaac0-dev** [comment]
not enough people report bugs, wdym?
plenty do

**Comment by EmeraldLoc** [comment]
Perhaps on github? I really find a lack of bugs, either that or its just really stable :/

**Comment by mr-sihc** [comment]
the emu was 4:3 lol i'm late, it might be using the luigi version

**Comment by unkn0wncvm1** [comment]
> the emu was 4:3 lol i'm late, it might be using the luigi version

then close the issue
