### ISSUE TITLE
Music cuts out when too many sound effects are playing.

### ISSUE THREAD

**Issue by DarkRTA** [djoslin0/sm64ex-coop#219]
**Describe the bug**
In some situations, a limit for the max amount of sounds that are playing at once can be reached causing parts of the music to cut out.
This is very easy to reproduce in Rainbow Ride as a lot of the moving platforms constantly emit sounds.

**Desktop (please complete the following information):**
OS: Arch Linux 
Kernel: 6.3.5
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
GPU: AMD Radeon RX 5600 XT
Memory: 16GB

**Comment by mr-sihc** [comment]
you is so fucing ugly

**Comment by DarkRTA** [comment]
I might have a potential fix for this involving increasing the size of several pools used for audio.

Gonna work on it and open a PR.

**Comment by DarkRTA** [comment]
fixed in dev branch
