### ISSUE TITLE
[Bug/Make] Missing file

### ISSUE THREAD

**Issue by LunarN0v4** [djoslin0/sm64ex-coop#224]
**Describe the bug**
A missing file in the root of the project

**To Reproduce**
1. make
2. profit!

**Expected behavior**
This is a bug with compilation of the binary, what's expected is for it to compile properly.

**Screenshots**
Not needed, it's happening within a terminal and can have the text copied out.

**Desktop (please complete the following information):**
 - OS: [arch]
 - Browser [firefox]
 - Version [unneeded]

**Additional context**
❯ make
==== Build Options ====
Version:        us
Microcode:      f3dex2e
Target:         sm64.us
Compare ROM:    no
Build Matching: no
=======================
Failed to open baserom.us.z64! [Errno 2] No such file or directory: 'baserom.us.z64'
Makefile:472: *** Failed to extract assets.  Stop.

**Comment by motoo-tobbler** [comment]
Greetings Arch Linux user,

I assume that you might have already solved this issue. If you have not, then place a dumped ROM file of the _North American_ version of _Super Mario 64_ for the _N64_, renamed as `baserom.us.z64`, in the root of the cloned repository.

As for  "A missing file in the root of the project", we are unable to provide the ROM to you, as it is the copyrighted work of Nintendo. Kindly obtain the ROM file yourself.

Happy Compiling!

**Comment by LunarN0v4** [comment]
> Greetings Arch Linux user,
> 
> I assume that you might have already solved this issue. If you have not, then place a dumped ROM file of the _North American_ version of _Super Mario 64_ for the _N64_, renamed as `baserom.us.z64`, in the root of the cloned repository.
> 
> As for "A missing file in the root of the project", we are unable to provide the ROM to you, as it is the copyrighted work of Nintendo. Kindly obtain the ROM file yourself.
> 
> Happy Compiling!
> ##### Btw I use arch too

Ahhh, I figured, thank you!!
