### ISSUE TITLE
Game Keeps On Crashing Regulary

### ISSUE THREAD

**Issue by 12abz** [djoslin0/sm64ex-coop#229]
**Describe the bug**
a crash that happens when im in a server and i go afk

**To Reproduce**
does not seem reproduceable happens randomly on my laptop

**Expected behavior**

**Screen
![Screenshot from 2023-08-17 17-27-26](https://github.com/djoslin0/sm64ex-coop/assets/109289447/745aaaf8-59ec-428c-9b26-0b6a3b33c0eb)
shots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Browser FireFox
 - Version beta 35

**Additional context**
crashes happend 6 times as of writing this

**Comment by 12abz** [comment]
Update: crashed 2 time

**Comment by 12abz** [comment]
Update Just Crashed right now

**Comment by yoyeet961** [comment]
thats normal its just fucked up packets or whatever

**Comment by Isaac0-dev** [comment]
crashes are unfortunately common, but we do appreciate crash reports. This specific crash is fixed for the next update.
