### ISSUE TITLE
Lost Connection to CoopNet

### ISSUE THREAD

**Issue by zackgreen16** [djoslin0/sm64ex-coop#231]
**Describe the bug**
Ex-coop doesn't let me join any games and says "Lost Connection to CoopNet"

**To Reproduce**
1. Go to 'Join'
2. Click on 'Public Lobbies'

**Expected behavior**
It's suppose to connect to CoopNet and show the public lobbies

**Screenshots**
![image](https://github.com/djoslin0/sm64ex-coop/assets/66157074/dbaae866-9fd2-4b3d-ab54-e4516874ae0a)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Browser: Opera GX
 - Version: Beta 35

**Additional context**
Ex-coop doesn't let me play the game at all saying "Lost Connection to CoopNet"
I can't even join Discord invites

**Comment by zackgreen16** [comment]
**Update**
It seems that CoopNet doesn't connect on my main router but it does on my alt router (which is slower), I don't know why or what is going on, If anyone could recommend some troubleshooting methods, reasons and other stuff I would be glad 

If you need the IP of my main router, DM me on discord at realzackgreen if you want to

**Comment by LukeOfGithub1107** [comment]
i cant connet i did every thing

**Comment by Aaronmathew19** [comment]
Of course I did the steps But it still keeps telling me that the connection to coopnet was lost Please can you look for another solution That is solved at night And at that time I have little left to play :(
