### ISSUE TITLE
black screen and crash

### ISSUE THREAD

**Issue by LazimCODER** [djoslin0/sm64ex-coop#236]
**Describe the bug**
When i open it it Shows a  black screen and it Comes an error Named "sm64.us.f3dex has stopped Working"

**To Reproduce**
1. Open
2. press W,A,S,D  or space

**Screenshots**
![image](https://github.com/djoslin0/sm64ex-coop/assets/119290479/8e24aec1-2881-4915-a1cc-25bdfe99c06c)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox
 - Version beta 35

**Additional context**
I cant start sm64ex coop

**Comment by yoyeet961** [comment]
what's your cpu and gpu?

**Comment by yoyeet961** [comment]
those are some really old specs, try using directx for your rendering api

**Comment by LazimCODER** [comment]
it works
