### ISSUE TITLE
linux not compiling sm64 ex coop?

### ISSUE THREAD

**Issue by y0wzers** [djoslin0/sm64ex-coop#243]
to put this in a nutshell, i have a baserom.us.z64 rom and when i tried to use linux to compile sm64 ex coop, it said
Failed to open baserom.us.z64! [Errno 2] No such file or directory: 'baserom.us.z64'
Makefile:472: *** Failed to extract assets.  Stop.
so how do i fix this?

**Comment by EmeraldLoc** [comment]
Is it in the sm64ex-coop folder? And is it named baserom.us.z64?

**Comment by y0wzers** [comment]
oh ok thx emerald i think that was the problem, im gonna go put it in the sm64ex-coop folder now.

**Comment by y0wzers** [comment]
ok so now i extracted the stuff how do i open it?

**Comment by EmeraldLoc** [comment]
Cd to the build/us_pc folder in your terminal, and run `./sm64.us.f3dex2e` I assume since your running linux you know how to do that so wont mention how

**Comment by y0wzers** [comment]
i kinda started using linux 1 week ago so could u do a short explaination on how to do that?

**Comment by y0wzers** [comment]
actually never mind i figured out how to use it
