### ISSUE TITLE
Pointer not aligned [macOS Sonoma]

### ISSUE THREAD

**Issue by MarioMastr** [djoslin0/sm64ex-coop#245]
**Describe the bug**
I was trying to build sm64ex-coop on a Mac and I'm consistently running upon this linking error right at the end.

**Screenshots**
<img width="682" alt="Screenshot 2023-09-26 at 23 04 33" src="https://github.com/djoslin0/sm64ex-coop/assets/84964352/89545158-b505-4a46-8901-a1183be83030">

**Desktop (please complete the following information):**
 - OS: macOS
 - M1 Macbook Air (8/7, 8G of RAM)

**Comment by MarioMastr** [comment]
this line of logfile.c is whats causing it to break,
{ .fileName = "discordlog.txt", .active = false, .firstOpen = true, .file = NULL }

**Comment by MarioMastr** [comment]
i fixed it
i had to copy the discord_game_sdk.dylib and libdiscord_game_sdk.dylib files into the x86 directory in the discord lib and it worked

**Comment by MarioMastr** [comment]
Nevermind no it didnt. Even the existence of a second line causes it to fail

**Comment by EmeraldLoc** [comment]
What version, sonoma, ventura, etc

**Comment by MarioMastr** [comment]
Sonoma

**Comment by EmeraldLoc** [comment]
Ah yes, good'ol sonoma, apple did some very goofy stuff.

So open up the Makefile in the sm64ex-coop folder, and your gonna wanna go to line 811, and change that line from

`BACKEND_LDFLAGS += -framework OpenGL `pkg-config --libs glew``

to

`BACKEND_LDFLAGS += -framework OpenGL `pkg-config --libs glew` -ld_classic`

That should fix it, only thing is I have not seen that specific error before, as when I was dealing with it, I was on a beta, but, we shall see. Also I would suggest naming this `Linker error on macOS Sonoma` for other ppl having the same problem, as this will be a common problem until the next version comes out.

**Comment by MarioMastr** [comment]
Ok cool
I'm not at my computer currently but I'll do that when I get to it :)

**Comment by MarioMastr** [comment]
cool it worked thanks a ton
p.s. i still got a warning regarding the unaligned pointers during this but it worked nonetheless
<img width="682" alt="Screenshot 2023-09-27 at 20 05 02" src="https://github.com/djoslin0/sm64ex-coop/assets/84964352/7ac61bc6-9246-4cd2-81cb-ce6816c93019">

**Comment by AbnormalPoof** [comment]
Even after compiling successfully, macOS kills the app for no reason at all.

`zsh: killed     ./build/us_pc/sm64.us.f3dex2e.app`

**Comment by TheOliveOli38** [comment]
I don't know if it's worth mentioning in the wiki entry, but executable linking fails with the -ld_classic option on older macOS versions (I'm on Big Sur) so you'd have to remove it if you want to be able to build successfully on these older versions.

**Comment by EmeraldLoc** [comment]
It has been removed, if it’s still there it is removed in the next versions
