### ISSUE TITLE
Commands to Kick/Ban/Permban doesn't work.

### ISSUE THREAD

**Issue by ZaneFlynt01** [djoslin0/sm64ex-coop#247]
**Describe the bug**
I was playing the game on a server running the Star Road hack, when a user named #dcdcdc joined and started spouting some inappropriate stuff, specifically saying "You. Me. Sex. Now" in chat. I used /players to get their ID, however, when I typed their name and/or player id into the command /permban [NAME/ID], it would say 'Could not find player'.

I tried with standard /ban and /kick only to get the same result.

(I personally would like to request that the owner of the server and moderators have a console that they can use to select people and more easily ban someone from the server who makes people uncomfortable, or breaks rules and such.)

May possibly caused by the fact their name was a color code, as the only places where their name appeared was in the chat and the message saying when they join/leave.

**To Reproduce**
1. Open Chat
2. Type /ban [Name/ID]
3. Execute the command

**Expected behavior**
Typing the player's name/id into the command would kick, ban, or permban the player respectively for whichever command was used.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [Beta 35]

**Comment by Amy54Desu** [comment]
I don't think you were using it right
