### ISSUE TITLE
Chat not Working

### ISSUE THREAD

**Issue by MistrRetro** [djoslin0/sm64ex-coop#256]
Maybe there is the possibility I don't know how the chat message sending works BUT when I first booted up SM64ex-coop I tried pressing the (what I believe was the key for chatting at the moment) space key again after I used it to open chat to send a message but it's didn't t work.
I also tried to rebind the key to Enter but it still didn't work. Does anyone know the solution?

**Comment by RRETR0MAN** [comment]
A little extra info, I don't have discord. My account got banned and I really don't wanna go back.

**Comment by EmeraldLoc** [comment]
I have no clue, my chat is binded to enter/return, and it works fine. It should show a input box at the bottom left, and you should be able to type on it. If your using mods, one of those may be blocking the input, so make sure to try it with no mods. Also it's not because you don't have discord, I don't either, so that's definitely not the problem. I would try binding it to a button you know works, like the key you use to move.

**Comment by MistrRetro** [comment]
Thanks for trying to help! Btw yes, I can open the box and type in it, the issue is with sending as I simply cannot send messages. It seems that, based off my testing, mods on my mod folder aren't interfering either.

**Comment by EmeraldLoc** [comment]
Oh thats bizarre, i'll look into that in a bit, currently busy with some stuff. In the meantime, while I dont think this will work, try binding it to say, p, and then try to send the message with enter/return. Also, see what happens when you press p when the inputbox is open.

**Comment by MistrRetro** [comment]
I tried that and it didn't work. Maybe it's related to the decompilation of the game? Because it didn't work even before I installed mods.

**Comment by EmeraldLoc** [comment]
From what I have seen, the enter key should send the message, what os are you running, and what keyboard do you have? Make sure you are hitting the return/enter button above the shift key

**Comment by MistrRetro** [comment]
I am using Windows and I have a image of my keyboard right here
![image](https://github.com/djoslin0/sm64ex-coop/assets/149272617/5edf1284-489f-4e79-8b7f-0ad15693680a)

**Comment by EmeraldLoc** [comment]
gotta get that netflix in, yea so just kinda hit a bunch of random keys on the keyboard, one of them will probably work.

**Comment by EmeraldLoc** [comment]
Wait I just noticed its shaped like a gun LOL

**Comment by MistrRetro** [comment]
You say you are a gamer, but do you have the GUNNER NETFLIX KEYBOARD? I think not!

Yeah I think none of the keys got recognized. I think that the developers should just add a way to map the send key so that situations like this can get avoided. For now I'll just be the guy who actually stfu.

**Comment by EmeraldLoc** [comment]
Ill look into making that a pr so this doesnt happen again, sorry for the inconvenience

**Comment by MistrRetro** [comment]
No need to say sorry! I don't mind it too much and it's not your fault anyways. It was just a unexpected scenario
