### ISSUE TITLE
[Question] Are more than 2 players allowed?

### ISSUE THREAD

**Issue by iProgramMC** [djoslin0/sm64ex-coop#26]
Title

If not, how would a server update enemies?

**Comment by djoslin0** [comment]
Nope, only two players. I may add more players eventually

**Comment by iProgramMC** [comment]
I see. How does the networking work?

**Comment by djoslin0** [comment]
The general idea is: whoever is closest to a synchronized entity becomes the 'owner' for that entity and sends updates about it's state to the other player. I just plain UDP sockets for sending packets.

**Comment by iProgramMC** [comment]
That's interesting. Isn't RUDP (reliable UDP) with libraries a better way
to handle this? Also, how would you go about updating the worlds server
sidedly, would you update every world or what

**Comment by djoslin0** [comment]
I added an option in my system for reliable UDP packets. They will continue to send until they're ACK'd by the other side. With most entities you only want their latest information though, so their packets are not sent reliably unless the packet contains an important event. Libraries would probably be a better way, but I enjoy writing low level packet stuff for some reason. I'm not sure what you mean with your other question.

**Comment by iProgramMC** [comment]
Have  you ever coded an MMO server? If not, let me give you an example:
Minecraft has entities which update 20 times per second on the server side
and send packets to each player.

An MMO is actually quite simple until you add updating things.

Mario 64 could work the same way, there would be a game loop going through
each world (from BOB to RR, and the other secret courses, except Ending,
because that has no enemies) and loading enemies and objects in, and
updating them 30 times a second (the SM64 frame rate) which could be
interpolated in the case of unlocked FPS patches. The game would send
interaction packets to the server, which would result in the enemy dying or
other activities.

Here's an example of how that could work:

* The player punches a Goomba
* The game sends a punch packet with the Goomba's Object ID in mind
* The server sees that the player has punched a goomba and kills it, then
sends a few object spawn packets (for particles and the coin) and a kill
packet for the goomba.

**Comment by djoslin0** [comment]
That's essentially how it works. Although particles and such are not sent in packets, those are just recreated locally because the event is happening. But entity creation is sent in an object spawn packet, one example is koopa shells.

**Comment by iProgramMC** [comment]
Oh, yeah, but that would require more clientside code

**Comment by djoslin0** [comment]
Closing thread, general discussion like this can happen on Discord:
https://discord.gg/MADa7eX
