### ISSUE TITLE
forced camera mode in custom levels

### ISSUE THREAD

**Issue by wingstosky255** [djoslin0/sm64ex-coop#272]
why is it forced to be 8 direction

**Comment by EmeraldLoc** [comment]
Assuming your creating a level, the camera mode is defined in fast64, and is not related to sm64ex-coop. If you are copying the romhack camera code, which is a camera similar to 8 directions, that is most likely your problem.

**Comment by wingstosky255** [comment]
I'm not using a romhack camera code in lua or something I only asked why does it force to be 8 direction
