### ISSUE TITLE
Display public IP in-game

### ISSUE THREAD

**Issue by djoslin0** [djoslin0/sm64ex-coop#28]
Reported by Birb
> It would also be nice to see what IP you need to use. Just putting it in the top left of the save menu and whenever you pause would make connecting easier, and faster (for time reasons). Don't know if that is possible, at all, but if you can that would be a nice addition.

**Comment by MegaMech** [comment]
What if someone doesn't want their IP displayed to others?

**Comment by djoslin0** [comment]
This was requested before the Discord API was a thing. In that case you had to share your public IP to connect.

**Comment by w3bb** [comment]
This probably wouldn't be good for streamers or people screen sharing who don't want to share their IP with people watching. I think a toggle would be a good solution.
