### ISSUE TITLE
ubuntu why :'(

### ISSUE THREAD

**Issue by gityman** [djoslin0/sm64ex-coop#281]
ubuntu distros (and possibly base ubuntu) keep crashing after a little while of play time, and when I mean crashing, I mean stopping the entire os somehow, wine or native, don't have screenshots obv.

**Comment by Paradox9955** [comment]
> ubuntu distros (and possibly base ubuntu) keep crashing after a little while of play time, and when I mean crashing, I mean stopping the entire os somehow, wine or native, don't have screenshots obv.

I don't have this issue. And this has never been reported before. So it's probably something to do with your setup. Which version of Ubuntu are you on?

**Comment by yoyeet961** [comment]
i can confirm coop doesnt crash my entire computer after playing it for a while. could it be that your pc is overheating? try capping your framerate to like 144 and tell me if it still crashes. tho i doubt that will help, but well i dont know anything more about this kind of stuff

**Comment by gityman** [comment]
fuck this nobody understood me
