### ISSUE TITLE
ban appeal

### ISSUE THREAD

**Issue by TroopaParaKoopa** [djoslin0/sm64ex-coop#291]
guys im very sorry for using my custom build oh wait uhhhhh IT'S A GLITCH A GLITCH a kkoopa SHEL GLITCH!!!!!!!! believe me guys i would never lie to you 😭 IM INSTALLING ORIGINAL COOP RIGHT NOW! 😭

**Comment by yoyeet961** [comment]
Are you gonna mock every single ban appeal? This just sounds stupid

**Comment by Flamarix** [comment]
If you think this is funny, it's messed up

**Comment by TroopaParaKoopa** [comment]
ah shucks

**Comment by Arabic64** [comment]
Stop mocking about him like bro wtf he did to you. Aren't you happy that you've lied about watchr begging you for nitro ? Then stop mocking about him that's all. He played a dev build and he will never do this again and you got banned from the coop server then you started mocking about him more and more and more. Oh yeah good news for ya, he got banned for one day.

**Comment by Arabic64** [comment]
If you want to yap about dramas OVER AND OVER AGAIN and ridding someone's dick or to piss them off. Your server is the perfect place to do this you know?
