### ISSUE TITLE
21 Second Star crash in PSS

### ISSUE THREAD

**Issue by anuserlol** [djoslin0/sm64ex-coop#32]
If you beat the slide before 21 seconds, as soon as you trigger the star, the game will freeze for a sec and crash.
**To Reproduce**
1. Go to The Princess's Secret Slide
2. Go down the Slide and get to the goal in less than 21 seconds
3. Crash

**Expected behavior**
A star should appear in front of the player.

**Additional context**
The other player (Luigi) crashes too.

**Comment by djoslin0** [comment]
What type of crash was it? Did it hang, did an error message pop up?

**Comment by djoslin0** [comment]
nevermind, happens right away
