### ISSUE TITLE
Warp Crash in CCM

### ISSUE THREAD

**Issue by anuserlol** [djoslin0/sm64ex-coop#33]
**Describe the bug**
If Mario enters the fireplace in the house at the top first, Luigi's game crashes.

**To Reproduce**
1. Go to Cool Cool Mountain
2. Make sure Luigi is out of the fireplace
3. Get Mario into the fireplace

**Expected behavior**
Both players should get warped inside.

**Screenshots**
https://cdn.discordapp.com/attachments/706919740031107142/752682405810405416/unknown.png
https://cdn.discordapp.com/attachments/706919740031107142/752682436650860554/unknown.png

**Additional context**
Idk if this may cause it, but we had 7 red coins collected.

**Comment by djoslin0** [comment]
Hmm, I can't figure this one out. I'll have to add stacktraces eventually to get a better idea of what's going on. I'll do more poking around

**Comment by djoslin0** [comment]
Closing as fixed, will reopen if these crashes come back
