### ISSUE TITLE
Invisible star on BOB

### ISSUE THREAD

**Issue by anuserlol** [djoslin0/sm64ex-coop#34]
**Describe the bug**
If Mario breaks the yellow box in the floating island (Luigi was in my case down at the ground not in the island), Luigi won't see the star later.

**To Reproduce**
1. Go to BOB
2. Break the box as Mario
3. DON'T COLLECT THE STAR YET
4. Make Luigi get on the island, he shouldn't see the star, he will see Mario do the correct animation as expected if he collects it.
(Not sure what happens if Luigi collects it without seeing it.)

**Expected behavior**
Both players should see the star.

**Additional context**
Seems to only happen with the golden one, and not the transparent one after it's been collected.

**Comment by djoslin0** [comment]
Hmm, Luigi sees the star for me. I'll try a few more times

**Comment by djoslin0** [comment]
I can get it to happen when I drop packets, hmmm
