### ISSUE TITLE
Lethal Lava Land Softlocks upon death

### ISSUE THREAD

**Issue by Meowstuffs** [djoslin0/sm64ex-coop#36]
If you die by falling into lava, you will be softlocked and constantly will hit the lava intead of entering a bubble.

Steps to reproduce:
1. Have both players enter LLL
2. Kill one of the players by throwing them into the lava
3. Softlock

pls fix

**Comment by djoslin0** [comment]
LLL isn't supported yet. I'll get there eventually, still working on stability for now
