### ISSUE TITLE
Clientside prediction sometimes break hit registration

### ISSUE THREAD

**Issue by Meowstuffs** [djoslin0/sm64ex-coop#39]
If you attempt to kick a person while they're moving, it sometimes won't register.
my guess is the clientside prediction makes it seem as if you were hitting them, so maybe there should be lag compensation

**Comment by Meowstuffs** [comment]
uploading video of the problem later, once handbrake compresses it

**Comment by djoslin0** [comment]
would require lag compensation, but that would have the reverse problem where you get hit when you feel like you shouldn't. I'll try to find a nice balance eventually

**Comment by djoslin0** [comment]
Will be improved in beta 33, future work may happen eventually
