### ISSUE TITLE
ACT 1 Cannon bug in BOB

### ISSUE THREAD

**Issue by anuserlol** [djoslin0/sm64ex-coop#43]
**Describe the bug**
If Mario selects act 1 in bob-omb battlefield after opening the cannons, they will be close for him, but not for Luigi. As soon as Luigi enters one it will get unlocked.

**To Reproduce**
1. Go to BOB
2. Choose Act 1
3. Make Luigi enter a cannon
4. All the cannons except the animated ones (the ones that shoot automatically) will be unlocked.

**Expected behavior**
None of the player should be able to enter any cannon at this point.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/16540103/92664902-87fb4980-f305-11ea-9955-23dddfaf4ed1.png)

**Comment by djoslin0** [comment]
This seems to be normal Mario 64 behavior. I tried it in sm64ex and the cannons were unlocked in act 1

![image](https://user-images.githubusercontent.com/12403224/92988458-8ace7980-f480-11ea-9ca3-936b31afc297.png)
