### ISSUE TITLE
Door Animation bug

### ISSUE THREAD

**Issue by eros71-dev** [djoslin0/sm64ex-coop#46]
**Describe the bug**
If the two player are able to open a door at the same time from both sides, they will go to the other room and then one of them (in my case Luigi, not sure if this happens everytime) will get teleported to the other player's room.

**To Reproduce**
1. Open a door with Mario on one side and Luigi on the other with both players at the same time
2. The animation will play like it should
3. Luigi (in this case) will get teleported to the room that Mario just entered

**Expected behavior**
The players should stay in their respective rooms

**Screenshots**
I wasn't able to capture one this time, sorry

**Additional context**
Does it even make sense for Mario and Luigi to go through each other at the door?

**Comment by djoslin0** [comment]
fixed in latest unstable
