### ISSUE TITLE
Camera gets stuck in BBH if player exits or enters room while the other one opens the door

### ISSUE THREAD

**Issue by anuserlol** [djoslin0/sm64ex-coop#48]
**Describe the bug**
If one player (Mario) inside **the room at the back** (only seems to happen with this one) of the "mansion" opens the door to exit and the other one (Luigi) runs out, the latest's camera (Luigi's) will get stuck in place and not follow the player.
_Not sure if this happens in any other rooms, doesn't seem to happen in the other ones we tried._

**To Reproduce**
1. Go to BBH
2. Make both players enter the room at the back of the Mansion
3. Make one of them (in my case Mario) open the door and do the animation
4. Make the other one (Luigi in this case) exit before the door closes
5. See error
(This seems to work both exiting from inside or coming from outside.)

**Expected behavior**
The camera should follow the respective player as usual.

**Screenshots**
Coming from outside:
![imagen](https://user-images.githubusercontent.com/16540103/92669723-ad428480-f312-11ea-9f1c-27f8b8aa58ce.png)
![imagen](https://user-images.githubusercontent.com/16540103/92670187-c1d34c80-f313-11ea-8776-81737d7e0fd0.png)

Getting out from inside:
![imagen](https://user-images.githubusercontent.com/16540103/92669777-cc411680-f312-11ea-8adb-0f760b94f7be.png)

**Additional context**
A lot of bugs in this level seem to happen when both players trigger something at the same time, I guess it happens on many other levels too, but this one is the easiest (for now) to test that out.

**Comment by anuserlol** [comment]
This seems to happen in the castle too, in a different way, if you open the door on the ground floor to go to the basement hall and come back to the ground floor before the door closes, the camera will get a similar effect:
![imagen](https://user-images.githubusercontent.com/16540103/92672854-f4804380-f319-11ea-910d-f2267bc7e2d7.png)
![imagen](https://user-images.githubusercontent.com/16540103/92672862-fb0ebb00-f319-11ea-99ab-3e0bf6b2e85b.png)

**Comment by djoslin0** [comment]
Did this happen with the default free cam or the vanilla camera?
I can't reproduce it with free camera, but the vanilla camera really doesn't like that I allow them to walk through the door

**Comment by anuserlol** [comment]
It happens with the vanilla camera. We normally don't use the free camera to test things out.
