### ISSUE TITLE
Bowser 1 softlock

### ISSUE THREAD

**Issue by somario360** [djoslin0/sm64ex-coop#5]
My friend (Mario) talked to Bowser after defeating him, Bowser turned into a key, but he was stuck in the looking up animation after (I was able to grab the key though, but Bowser was slightly visible) (Also don't mind 0 stars, he loves doing the lobby BLJ)
![sm64 us f3dex2e_2020-08-31_18-02-27](https://user-images.githubusercontent.com/22121742/91777036-6935de00-ebb4-11ea-8733-f09cd391ed0e.jpg)

**Comment by djoslin0** [comment]
Fixed as of https://github.com/djoslin0/sm64ex-coop/commit/efa1600ad058c7c6e2876aac8311f6fe68950ffe
Let me know if I should reopen this issue.
