### ISSUE TITLE
Blinking screen on star select if both players enter a level at the same time

### ISSUE THREAD

**Issue by anuserlol** [djoslin0/sm64ex-coop#50]
**Describe the bug**
If Mario and Luigi enter the same stage (BBH in our case, again) at the same time, the star select screen will start blinking for one of the players.

**To Reproduce**
1. Go to BBH
2. Make Mario and Luigi enter the cage at the same time
3. See error

**Expected behavior**
The star select screen should not repeat the transition over and over.

**Comment by anzz1** [comment]
I could also reproduce this bug every time even without entering at the same time, but rather it being linked with both players dieing.

**To Reproduce**
1. Go to Whomp's Fortress
2. Both players die and get thrown out of the level.
3. Which one died first (and was bubbled when second one died) will get blinking star select screen when entering a level. It does not matter whether he goes into a painting (to be the star selector) or not , he will get blinking screen either way.

**Comment by djoslin0** [comment]
Still not fixed
