### ISSUE TITLE
Star select soft-lock

### ISSUE THREAD

**Issue by anuserlol** [djoslin0/sm64ex-coop#51]
**Describe the bug**
Happened randomly, doesn't seem to be able to workaround. Sometimes, if a player enters a level, the other player will see the first player selecting a star, but after choosing it, Luigi won't move on Mario screen or will go in a specific direction until he collides with an object or the level. Luigi (the client) will see again the star select screen, even if Mario Exits the course and enters the same one or another one. Luigi can still see Mario selecting which star to collect.

**To Reproduce**
1. Happens randomly, not really sure why it happens. Sorry.
EDIT: I think you can force it too if you enter SSL

**Expected behavior**
Luigi should be still able to join Mario like always.

**Screenshots and logs**
Client invalid SyncObject!
Client invalid SyncObject!
Client invalid SyncObject!
Client invalid SyncObject!
Client invalid SyncObject!
Client invalid SyncObject!
Client invalid SyncObject!
ERROR: failed to find spawn object's parent (29)!
--Type <RET> for more, q to quit, c to continue without paging--Quit
(gdb)
![imagen](https://user-images.githubusercontent.com/16540103/92816666-12a37d80-f3c6-11ea-8bfe-c11c59f8f9f6.png)

(gdb) bt
#0  0x00000001400d93b7 in obj_angle_to_object (
    obj1=0x140f58dd8 <gObjectPool+10808>, obj2=0x0)
    at src/game/object_helpers.c:404
#1  0x00000001400036bf in cur_obj_update () at src/engine/behavior_script.c:982
#2  0x00000001400e1a12 in update_objects_starting_at (
    objList=0x1410c0f40 <gObjectListArray+1248>,
    firstObj=0x140f58dd8 <gObjectPool+10808>)
    at src/game/object_list_processor.c:308
#3  0x00000001400e1b82 in update_objects_in_list (
    objList=0x1410c0f40 <gObjectListArray+1248>)
    at src/game/object_list_processor.c:376
#4  0x00000001400e21d1 in update_non_terrain_objects ()
    at src/game/object_list_processor.c:598
#5  0x00000001400e246a in update_objects (unused=0)
    at src/game/object_list_processor.c:681
#6  0x000000014001147e in area_update_objects () at src/game/area.c:316
#7  0x0000000140112a60 in lvl_update_obj_and_load_act_button_actions (arg=0,
    unused=0) at src/menu/star_select.c:455
#8  0x00000001400071ca in level_cmd_call_loop ()
    at src/engine/level_script.c:241
#9  0x0000000140008f59 in level_script_execute (
--Type <RET> for more, q to quit, c to continue without paging--

![imagen](https://user-images.githubusercontent.com/16540103/92816638-0ddec980-f3c6-11ea-93b8-d7d7a5c6611a.png)

Only Luigi crashed

**Comment by djoslin0** [comment]
I'm trying to figure out the order of events here:
[1] mario enters a level
[2] luigi sees mario selecting star
[3] mario chooses star
[4] mario sees an invalid/inactive luigi
[5] luigi stuck in the same star select screen shown on [2]
Is this correct?

**Comment by anuserlol** [comment]
That's what happened, yes

**Comment by djoslin0** [comment]
so Luigi never saw the level load?

**Comment by anuserlol** [comment]
No, he was always stuck on the select screen

**Comment by Jarfeh** [comment]
This still seems to be an issue, even after re-compiling

**Comment by djoslin0** [comment]
@Jarfeh do you remember anything specific about the time it happened to you, and how I might reproduce it?

**Comment by Jarfeh** [comment]
The only time it happens is when the host (Mario) jumps into a painting where there is more than one star available to select. It never happens when Luigi jumps through.

**Comment by djoslin0** [comment]
Does this still happen? I haven't heard any reports about this in quite a while. Tempted to close it unless it shows up again

**Comment by Jarfeh** [comment]
I'll have to test the next time I compile

**Comment by Jarfeh** [comment]
It seems to be resolved.

**Comment by djoslin0** [comment]
Glad to hear it
