### ISSUE TITLE
Add mouse control to menu and ability to paste IP with right-click

### ISSUE THREAD

**Issue by anzz1** [djoslin0/sm64ex-coop#59]
Mouse control for title screen and menu's has already been done in this sm64ex PR : https://github.com/sm64pc/sm64ex/pull/406/commits/4ea9fad1615b1be9dfdfab07d8490e878abd4dd1

With that also could be added ability to paste the host's IP from clipboard by right-clicking the mouse in the "Join game" screen. In Windows this is as simple as using GetClipboardData() win32 api function.

**Comment by djoslin0** [comment]
in latest unstable
