### ISSUE TITLE
Baby Penguin Softlock

### ISSUE THREAD

**Issue by somario360** [djoslin0/sm64ex-coop#6]
After I (Luigi) gave the baby penguin to the mother, the start spawned, but I was stuck in the looking up animation.
![sm64 us f3dex2e_2020-08-31_18-19-52](https://user-images.githubusercontent.com/22121742/91778048-16115a80-ebb7-11ea-8435-b57258c22da6.jpg)

**Comment by djoslin0** [comment]
Fixed as of https://github.com/djoslin0/sm64ex-coop/commit/efa1600ad058c7c6e2876aac8311f6fe68950ffe
Let me know if I should reopen this issue.

**Comment by djoslin0** [comment]
Managed to softlock myself again when looking into other penguin bugs
