### ISSUE TITLE
Key does not appear after beating BitFS

### ISSUE THREAD

**Issue by boardfish** [djoslin0/sm64ex-coop#65]
**Describe the bug**
Same as in title. Luigi got the kill, but we weren't credited with a key. This may have been fixed already, but as at 1e6c734, it hasn't. 

**Desktop (please complete the following information):**
 - OS: macOS High Sierra

**Additional context**

This is from an outdated version, so it might've already been fixed.

**Comment by sonic23145** [comment]
https://youtu.be/dqovCtMusVs

**Comment by boardfish** [comment]
I've been able to make it this far in spite of that without too many noticeable issues, and the maintainer is putting out fixes beyond BitDW, including the LLL softlock after death by lava. So I'm not sure that notice is entirely true.

**Comment by djoslin0** [comment]
That notice is true, I'm only looking into bugs up to Bowser 1 currently. The LLL softlock was because I was fixing up other bugs and ran across the line of code on the way there

**Comment by djoslin0** [comment]
fixed in 44c5b5b02b4da154b1882bc1e84fab9a9ec2ff01
