### ISSUE TITLE
Desync when joining while host is in different level

### ISSUE THREAD

**Issue by anzz1** [djoslin0/sm64ex-coop#68]
Build version: git-4acbbb4

**Describe the bug**
Host level/game state is not properly passed to Guest if he joins when Host is somewhere else than where the game begins, frontyard of Peaches castle.

**To Reproduce**
1. Host creates a server.
2. Guest joins.
3. Host goes to a level or different state of transition, like the backyard or basement of Peach's castle.
4. Guest disconnects.
5. Guest joins back and will start from the beginning at front of the Peaches castle. Host continues wherever he is and they are now desynced.
6. Game state will normalize again when new transition occurs, for example if Guest goes inside the castle or Host exits the course.

**Expected behavior**
Guest should have the proper level/state when joining.

**Screenshots**
![ss](https://user-images.githubusercontent.com/13628128/93948073-1c25d180-fd46-11ea-990e-c15553d60f06.png)

**Comment by anzz1** [comment]
This is somewhat fixed in 168a41f0f691ba1eb739fa534513f7680059384a as player packets are now dropped when in different level/area so now the player's join each other on the next transition consistently. 

Still it would be even better to have the guest join whichever area/level the host is in, but this could be now relabeled as a low-priority enhancement rather than a bug.

**Comment by djoslin0** [comment]
Joining a level after it has already begun would take a massive amount of work due to how many different problems it could cause. I was originally going to 'fix' this by forcing the client into a "Waiting for level transition" screen and inform the host that the other player is waiting for them to switch levels
