### ISSUE TITLE
Using the file select options won't write to the save file

### ISSUE THREAD

**Issue by Marioiscool246** [djoslin0/sm64ex-coop#69]
Using copy or erase will not write to the save file which can cause save file desyncs between the host and remote.

Version: 39a30093

**Comment by anzz1** [comment]
This is because network is not initialized yet and saving will not work when network type is NT_NONE. I made a pull request #70 to fix this but it's not the most elegant solution. It works though. Let's see if the maintainer wants to refactor it or use as-is.
