### ISSUE TITLE
Bowser Dialogue Reset

### ISSUE THREAD

**Issue by somario360** [djoslin0/sm64ex-coop#74]
Whenever a player is put in a bubble or is released from a bubble, the camera will focus on Bowser and will repeat the dialogue for that Bowser fight. This crashed my game the 2nd time this happened while fighting Bowser 2, the first being when he clipped through the floor after it tilted.

**Comment by djoslin0** [comment]
Fixed in next update

**Comment by djoslin0** [comment]
Fixed by b9813acbc58b6ca4e7bb91d9703b4e380da822a0
