### ISSUE TITLE
Add original luigi voices

### ISSUE THREAD

**Issue by sodomon2** [djoslin0/sm64ex-coop#75]
i realized that luigi's character does not have his original voice but uses mario's

and wanted to know if you plan to implement lugi's voices

**Comment by toonjoey** [comment]
Luigi didn't have a voice in Mario 64, the clips online were mistakenly taken from Mario Advance.

Would be cool to have a higher pitched Mario voice though.

**Comment by sodomon2** [comment]
but here is a mod that brings the voices, can't you use those voices?

https://docs.google.com/document/d/1O1AmmKFSkbgijruyMAIXHG6-_ial3_OpGj4u4bx2qmE/

**Comment by sodomon2** [comment]
I will close this as soon as it is ready.
