### ISSUE TITLE
Luigi's cap turns into Mario's when dropped [Enhancement]

### ISSUE THREAD

**Issue by anuserlol** [djoslin0/sm64ex-coop#78]
**Describe the inconsistency**
When Klepto steals Luigi's cap, the model shown in the floor or attached to Klepto will be Mario's cap.

**To Reproduce**
1. Go to SSL
2. Go near Klepto
3. Wait for it to steal Luigi's cap.
4. See problem

**Expected behavior**
Luigi's cap model should be placed instead.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/16540103/95794058-55b78000-0ce7-11eb-9caa-5644d698cff7.png)

**Additional information**
It's probably not a bug.

**Comment by anzz1** [comment]
Yeah in Tall, Tall mountain too when the monkey (the 1st lower one) steals luigi's cap, it will be marios cap in his head.
