### ISSUE TITLE
Ghost(?) Player

### ISSUE THREAD

**Issue by somario360** [djoslin0/sm64ex-coop#8]
My friend (Mario) was in a text box with Koopa the Quick and I took the warp at the mountain to get a quick time, but when I took the warp I saw my friend there with no animation. After the race started he went away.
![sm64 us f3dex2e_2020-09-01_13-51-38](https://user-images.githubusercontent.com/22121742/91894098-bec4c600-ec5a-11ea-81db-2b63f563736a.jpg)

**Comment by djoslin0** [comment]
Fixed in https://github.com/djoslin0/sm64ex-coop/commit/c54063fadda11ffa3dbd29915385a516fb2a55bc
