### ISSUE TITLE
No Hitbox Baby Penguin

### ISSUE THREAD

**Issue by somario360** [djoslin0/sm64ex-coop#9]
When my friend (Mario) picked up the baby penguin and set him down, the baby penguin lost collision for me (Luigi). This only happens when Mario picks up the baby penguin first.

**Comment by djoslin0** [comment]
I can not reproduce this. Can you think of any other events that happened where the penguin was involved?

**Comment by somario360** [comment]
When we discovered this, we exited the course and tried it again right after entering the course and the same happened. Tomorrow I will try to get a video of us reproducing the glitch.

**Comment by djoslin0** [comment]
Thanks that could be helpful. Try it on the latest build as I did push a couple of fixes for the penguins, no clue if it will help the situation though.

**Comment by somario360** [comment]
Okay, while I was recording the video we found out how to reproduce it. It only happens after you drop the penguin by crouching. You can still pick him up if Mario sets down the penguin with the punch button.

**Comment by djoslin0** [comment]
Ah, yep that does it. Interesting, thanks for figuring out the repro steps
