### ISSUE TITLE
Crash When Selecting "Exit Course" After Network Shutdown

### ISSUE THREAD

**Issue by Marioiscool246** [djoslin0/sm64ex-coop#92]
Reproduction steps:
1. Go into a level
2. Cause the host to disconnect
3. On the remote client, pause the game and exit course
4. Have the game crash

Also here's a suggestion: Allow returning to the main menu so you can host a new game or connect to someone else without closing the game out

**Comment by EmeraldLoc** [comment]
This is now fixed, as the player is spat in the main menu on disconnect.

**Comment by Marioiscool246** [comment]
Since the new menu changes I'm pretty sure this has been fixed
