### ISSUE TITLE
Android Port ?

### ISSUE THREAD

**Issue by Lucaspec72** [djoslin0/sm64ex-coop#93]
Would it be possible to port this to android ? playing this on a androidTV would be awesome

**Comment by MasterGamingYT** [comment]
Very unlikely since Discord Mobile doesnt support game invites. Also, direct connections will probably be difficult to implement, let alone the port forwarding. If you want to play it, then install linux and do it that way

**Comment by Lucaspec72** [comment]
That's unfortunate... although port forwarding isn't really a android problem, making users connect to a dedicated server instead of being p2p could make it somewhat usable (maybe kinda like net64+ ? idk sm64coop's inner workings). It makes sense that android compability is not considered though because there are maybe 10 players at most that would be interested in it (and the mod is focused on PC). With some luck someone will make a android fork in a year or two. Will definitely keep playing this on pc though =D
