### ISSUE TITLE
[Question] So why the sm64ex coop, only run on 60fps and no draw distance?

### ISSUE THREAD

**Issue by Poyozito** [djoslin0/sm64ex-coop#94]
Soo my pc is not that good, soo i run the game sm64ex, 30fps and limit draw distance to my game dont have slow down, so after i descover have a way to play super mario 64 online and no emulator, i try out, i build the game via sm64pcbuilder 2, after try out i got a massive slow down on bomb-ob battle field, because of 60 fps and no draw distance, why is necessary to use 60 fps and no draw distance, no option to disable?

**Comment by djoslin0** [comment]
The 60fps patch that is provided in the community does not have an option to toggle it on and off dynamically, and adding one in would be a big pain. If someone made it adjustable at runtime I would be happy to merge it.
Draw distance is tied to spawning logic in Mario, and therefore had to be infinite to sync enemies properly. I could add a new adjustable draw distance in that isn't tied to any game logic but it hasn't been a priority for me. This would be a lot less effort, so I could see myself doing it in the future. Again, if someone were to do this I would be happy to merge it.

**Comment by djoslin0** [comment]
I've added issue #96 to track the draw distance idea

**Comment by Poyozito** [comment]
> I've added issue #96 to track the draw distance idea

Thx man for replying me
